### ISSUE TITLE
Enumeration of tasks

### ISSUE THREAD

**Issue by clops** [lavary/crunz#10]
Whenever I run `crunz schedule:list` the list that is generated marks all entries with the # 1, example below:

> $ ./crunz schedule:list
> +---+----------------------------------+----------------+------------------------------+
> | # | Task                             | Expression     | Command to Run               |
> +---+----------------------------------+----------------+------------------------------+
> | 1 | Garbage Collect Expired Sessions | 0 * * * * *    | ./console cron sessions -q   |
> | 1 | Collect Stats from Previous Day  | 30 0 * * * *   | ./console stats:collect -q   |
> | 1 | General Garbage Collector        | 45 1 * * 7 *   | ./console cron garbage -q    |
> | 1 | Process Events                   | * * * * * *    | ./console cron events -q     |
> | 1 | Reminders Level 1                | 50 11 * * * *  | ./console cron reminders1 -q |
> | 1 | Reminders Level 2                | 40 11 * * * *  | ./console cron reminders2 -q |
> | 1 | Reminders Level 3                | 30 11 * * * *  | ./console cron reminders3 -q |
> | 1 | Scheduled Promotions             | */15 * * * * * | ./console cron promote -q    |
> | 1 | Shuffle and Stay on Top Control  | 0 */2 * * * *  | ./console cron shuffle -q    |
> +---+----------------------------------+----------------+------------------------------+

I would expect the "number" column to be incremented by one for each row.

**Comment by lavary** [comment]
Please update the package and check again.
Thanks for reporting this.

**Comment by clops** [comment]
Thanks, looks good :)

On Tue, Apr 26, 2016 at 12:09 PM, M. Reza Lavaryan <notifications@github.com
