### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by clops** [lavary/crunz#11]
In the current setup debugging is hard as there is no way to test discrete cronjobs for if they perform well without sending them to the crontab.

Would be nice to have the following additional options for the command `schedule:run`
- Task --> to indicate which task number from schedule:list is to be run now
- Force --> force run the task immediately and don't match a specific timespot

would make implementing && testing much more fun

**Comment by PabloKowalczyk** [comment]
Fixed by https://github.com/lavary/crunz/pull/120 and https://github.com/lavary/crunz/pull/129.
