### ISSUE TITLE
How to run a clojure that accepts objects as arguments

### ISSUE THREAD

**Issue by mindcreations** [lavary/crunz#115]
If I give a clojure to the run() method and for example I pass an $object of type Job

```php
    $schedule->run(function() use ($object) {
    // ... my code ...
    })->on(sometime)
```
I get this notice

> PHP Notice:  {closure}(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "Job" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition  in .../vendor/jeremeamia/SuperClosure/src/SerializableClosure.php(210)

followed by 

> PHP Fatal error:  Class name must be a valid object or a string in .../vendor/jeremeamia/SuperClosure/src/SerializableClosure.php(210) : eval()'d code on line 4 PHP Stack trace: 

This is correct because the definition of **Job** has not been included in any place.

How should I approach this if I pass an argument that is not known to the scheduler?
Also, if it can work as suggested by the PHP notice, where have I to put an __autoload() or spl_autoload_register() statement?

**Comment by PabloKowalczyk** [comment]
Interesting. Do you use globally installed Crunz?
This should work by default because Crunz, should, use autoloader provided by you project which is provided by Composer.

**Comment by mindcreations** [comment]
No, locally installed Crunz.
In fact there is no autoloader because it is an OLD, OLD project which also uses PHP 5.6
At this point I think that the legacy codebase should be refactored to use autoloading, at least for the classes that are used within the Crunz closure.

**Comment by PabloKowalczyk** [comment]
In this case you can add specific files to Crunz autoloader - https://getcomposer.org/doc/04-schema.md#files, should work even with very old project.

**Comment by mindcreations** [comment]
It worked! But I've not added the specific files to Crunz autoloader but rather in the composer.json of my project.

**Comment by PabloKowalczyk** [comment]
> ...  in the composer.json

This is exactly what i mean :)
