### ISSUE TITLE
appendOutputTo

### ISSUE THREAD

**Issue by clops** [lavary/crunz#12]
I nice to have would be to include the current timestamp when adding Log Output to a file.

**Comment by Ulbrec87** [comment]
Something like " (date && yourcommand) >> /yourlogfile/) " ?

**Comment by clops** [comment]
Exactly

**Comment by clops** [comment]
update: when I do scheduler:run from the console, the output is just fine to be added to the log file

```
[2016-04-28 18:02:49] Running scheduled command: Process Events
/Users/clops/Sites/xxxxxxxxx/console cron events -q > /dev/null 2>&1 &
```

**Comment by Ulbrec87** [comment]
You can use before method. Example:

```
$schedule = new Schedule();
$output = '/tmp/log_ls.log';
$schedule->run('ls')->everyMinute()
  ->description('List')
  ->appendOutputTo($output)->before(function() use ($output) {
  error_log("----[" . date('Y-m-d H:i:s' . "]----\n"), 3, ($output));
});
return $schedule;
```

If all of you agree, I will add a method in Event class to log timestamp in output file... or someone have another solution ?

**Comment by clops** [comment]
I am fine in using a dedicated before method for _one_ task, but what if I have a dozen? Duplicating code feels wrong here, would be awesome if the tool could do this "out of the box" :)

**Comment by Ulbrec87** [comment]
Why duplicating code? The method is in Event class, is centralized. Something like
`$schedule->run('ls')->everyMinute()
  ->description('List')
  ->appendOutputTo($output)->withTimestamp()`

or we can insert timestamp in implicite way when you call appendOutputTo($output).... I don't have any other ideas, what do you suggest? :)

**Comment by clops** [comment]
In case ->appendOutputTo($output)->withTimestamp() works already, then I am
more than fine using it :)

**Comment by PabloKowalczyk** [comment]
@clops issue fixed in https://github.com/lavary/crunz/pull/46 and merged to `master` branch.
