### ISSUE TITLE
Closure run and $var value not updated

### ISSUE THREAD

**Issue by mindcreations** [lavary/crunz#124]
This is a clarification request on this snippet of code.

    $schedule = new Schedule();
    $var = 1;

    $schedule->run(function() use ($var) {
      echo $var; // Prints 2
      $var++;
    })
    ->before(function() use ($var) {
      echo $var; // Prints 1
      $var++;
    })
    ->after(function() use ($var) {
      echo $var; // Prints 2
    })

As I can see the execution flow is:

1. before()
2. run() executed in thread so the value of $var++ is never returned back (ie lost after thread execution)?
3. after()

Now, in after() I have $var = 2 but I need it with value = 3.

How can I achieve this?

Thanks in advance.

**Comment by PabloKowalczyk** [comment]
Hello, you are correct about the flow, also  `run()` Closure is called in child process so there is no way to print 3 in `after()`. Maybe you can merge those three stages into one - `run()`?

**Comment by mindcreations** [comment]
I've already did it. 
I was wondering if there is a more elegant way to use before() and after() in a scenario like this.

**Comment by PabloKowalczyk** [comment]
Since Closure passed to `run()` is serialized to be run as child process there is no way to exchange data with before/after callbacks on the language level (by reference). You can exchange data by file/db/memory/anything-you-want :) but IMO this is far beyond a scope of Crunz itself.

**Comment by mindcreations** [comment]
I agree with you.
