### ISSUE TITLE
Ability to change lock directory

### ISSUE THREAD

**Issue by IkeLutra** [lavary/crunz#125]
*Scenario*

Running crunz in docker containers but still wanting to use the preventOverlapping feature using a shared volume.

*Current Behaviour*

Crunz always uses the system temp directory. It also requires on POSIX systems for all crunz jobs to be running in the same execution environment as it checks whether the pid in that file is still running. This prevents using shared file systems but different execution environments.

*Proposed Behaviour*

No changes to the defaults but adding the ability to change the lock directory and disable the checking of pids (e.g. drop to windows file only mode).

I have made a first attempt at this on this fork: https://github.com/AgePartnership/crunz/commit/0a45f0af847ab8126347b1df7dede5a64000655d

Let me know your thoughts?

**Comment by PabloKowalczyk** [comment]
Implemented in #153 and merged. Thanks @IkeLutra.
