### ISSUE TITLE
5 is not a valid position

### ISSUE THREAD

**Issue by clagio** [lavary/crunz#126]
Hello,

I tried to create a new task with command make:task as your example:
 vendor/bin/crunz make:task exampleOne --run scripts.php --in /var/www --frequency everyHour

But when I try to execute it, I have the following error:

> vendor/bin/crunz schedule:run
> In FieldFactory.php line 46:
>  5 is not a valid position
> schedule:run [\<source>]

The task file has been created, and the task:list command is listing it

**Comment by clagio** [comment]
I investigated a bit, and I think the issue is a bit tricky..
The error happens, because laravel 5.6 (which I'm using) require the package dragonmantank/cron-expression. Seems that this package doesn't support anymore the 6th character for the year, and seems that this package is used instead of mtdowling/cron-expression..
Not sure what is the best way to fix it..

**Comment by mindcreations** [comment]
An idea maybe adding an IF in the code making a different call according to the used package, this way it will be retrocompatible.

**Comment by PabloKowalczyk** [comment]
Hello, thanks for your report and investigation @clagio! IMO the best way to fix this issue is to switch to `dragonmantank/cron-expression`, i believe we can preserve BC, but we also should check if someone uses deprecated `mtdowling/cron-expression` and do some proper "ifs". In `v2` we can also add "conflict" with `mtdowling/cron-expression` (in `composer.json`).
Would you like to provide PR @clagio?

**Comment by clagio** [comment]
I think that switching to dragonmantank/cron-expression shouldn't be a big issue, but it really depends on how many changes there are between the two versions. The sixth character is not mandatory, so I suppose it's possible just ignore it even if it's provided and write in the readme that is not supported?

I'm in the process of learning php so I'm not sure i'm the right person to provide a PR, but I will look into it

**Comment by PabloKowalczyk** [comment]
After some investigation i found out that `dragonmantank/cron-expression` has the same API as `mtdowling/cron-expression` so fix for `5 is not a valid position` can be easier.
As you said @clagio there is no year support in `dragonmantank/cron-expression` but Crunz doesn't use `year` part actually so i deprecate using six parts cron expression and limit parts to 5 to provide forward-compatibility. You can test my changes if you want: https://github.com/lavary/crunz/pull/131.

**Comment by PabloKowalczyk** [comment]
I'm closing this issue because #131 was merged. Thanks @clagio for report.
