### ISSUE TITLE
multiple crunz installations on same server causing  conflict on writing in /tmp/crunz folder

### ISSUE THREAD

**Issue by pwsebbi** [lavary/crunz#128]
We have setup the same application in different webspaces on same server. This causing writing permissions error in the servers "/tmp/crunz" folder. I think we should instead use relative path like "tmp/crunz/" so we can put temporary files in each webspace's root instead?

**Comment by PabloKowalczyk** [comment]
Hello, use of relative path will result garbage in place where you invoked Crunz. Temporary fix is to delete Crunz temp directory after every run of `crunz run:schedule`, as a fix i propose to save Crunz temp files per user. WDYT?

**Comment by PabloKowalczyk** [comment]
I reworked cache directory logic in https://github.com/lavary/crunz/pull/132 and now Crunz will try to write cache in `/tmp/.crunz/<current-user>/<crunz-version>`. The `/tmp/.crunz/` should be created with 777 permissions so everyone could write to it. There is also a fallback if cache directory is not writable - compile container in runtime.
These changes should fixes your issue.
