### ISSUE TITLE
Empty error when invoking global function

### ISSUE THREAD

**Issue by esetnik** [lavary/crunz#134]
Example:

`TestTasks.php`
```
<?php

use Crunz\Schedule;

$schedule = new Schedule();

function test($parameter)
{
    echo 'test2';
}

$schedule->run(function () {
    echo 'test';

    test(true);
})
->everyMinute()
->description('Test schedule');

return $schedule;

```

Output:
`[2018-09-04 17:44:02] crunz.ERROR: Test schedule(object(Closure))    [] []`

**Comment by PabloKowalczyk** [comment]
This is the same case as here: https://github.com/lavary/crunz/issues/124
Crunz run all tasks as child processes so there is no way to share global functions without using any kind of autoloader (or `require`). Does it solve issue?

**Comment by esetnik** [comment]
This issue is not #124 rather another example of #135. I understand that global functions won’t work, but there should be error output if the user does try to erroneously use one. In #135 we addressed the reasons why error output is missing, so this can be closed as a duplicate.

**Comment by esetnik** [comment]
Additionally it would be good to document the limitations of the closure. E.g. global functions and complex objects cannot be captured.
