### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by t-me** [lavary/crunz#160]
**Crunz version**: 1.10
**PHP version**: 7.1
**Description**  
When i do a composer require lavary/crunz it tells me that "Your requirements could not be resolved to an installable set of packages." 

**Possible Solution**  
look if its compatible with nestbot/carbon 1.25

**Additional context**  
Problem 1
    - lavary/crunz v1.10.1 requires nesbot/carbon ^1.21 -> satisfiable by nesbot/carbon[1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0] but these conflict with your requirements or minimum-stability.
    - lavary/crunz v1.10 requires nesbot/carbon ^1.21 -> satisfiable by nesbot/carbon[1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0] but these conflict with your requirements or minimum-stability.
    - Installation request for lavary/crunz ^1.10 -> satisfiable by lavary/crunz[v1.10, v1.10.1].

**Comment by t-me** [comment]
{
    "require": {
        "tracy/tracy": "^2.5",
        "nesbot/carbon": "^2.5",
        "mailgun/mailgun-php": "^2.6",
        "php-http/curl-client": "^1.7",
        "guzzlehttp/psr7": "^1.4",
        "guzzlehttp/guzzle": "^6.3"
    }
}

**Comment by PabloKowalczyk** [comment]
Hello, upcoming `1.11` release will not depend on `nestbot/carbon` anymore. As a temporary fix you can use beta release `v1.11.0-beta.1` which do not depend on `nestbot/carbon`.
Command: `composer  require lavary/crunz:v1.11.0-beta.1`.

**Comment by PabloKowalczyk** [comment]
`v1.11.0` is stable now and no longer depends on `nestbot/carbon`. If version `v1.11.0` doesn't solves your problem feel free to open new issue.
