### ISSUE TITLE
Incorrect timezone in output_log_file

### ISSUE THREAD

**Issue by SadeghPM** [lavary/crunz#175]
Crunz timezone in output_log_file is not depending on timezone that is used to calculate task run time.

**Comment by PabloKowalczyk** [comment]
Hello, currently it uses PHP default timezone (or system default timezone) and this should be ok for users reading logs. Why you think that using timezone used to calculate task run time is better?

**Comment by SadeghPM** [comment]
Hi @PabloKowalczyk 
Because crunz logs my task related event. I set timezone for my tasks, and crunz uses this timezone to run task, thus any logs that related to this task, should be log in configured timezone.

**Comment by PabloKowalczyk** [comment]
So, what about new switch in config file: `timezone_log_timestamps`? Default value will be `false`, to keep current behavior, but users can switch it to `true` to have behavior described in this issue.
WDYT?

**Comment by SadeghPM** [comment]
I think current behavior with timezone option is strange and because timezone option is very important and not setting it is deprecated and will result in exception in 2.0 version, setting log file timezone by default on timezone option without any customization.

**Comment by PabloKowalczyk** [comment]
`timezone_log_timestamps` switch is needed to provide BC layer, the default behavior can change only on new major version.

**Comment by PabloKowalczyk** [comment]
PR #178 merged into `v1.12.x`. Thanks @SadeghPM.
