### ISSUE TITLE
 Undefined variable: input TaskGeneratorCommand.php on line 118

### ISSUE THREAD

**Issue by 1988luis** [lavary/crunz#18]
cmd: vendor/bin/crunz make:task demo1 --run demo1.php --in /var/www/html/crunz/tests
exception:
PHP Notice:  Undefined variable: input in /var/www/html/crunz/src/Console/Command/TaskGeneratorCommand.php on line 118
PHP Notice:  Undefined variable: output in /var/www/html/crunz/src/Console/Command/TaskGeneratorCommand.php on line 118
PHP Catchable fatal error:  Argument 1 passed to Symfony\Component\Console\Helper\QuestionHelper::ask() must implement interface Symfony\Component\Console\Input\InputInterface, null given, called in /var/www/html/crunz/src/Console/Command/TaskGeneratorCommand.php on line 118 and defined in /var/www/html/crunz/vendor/symfony/console/Helper/QuestionHelper.php on line 45

**Comment by lavary** [comment]
This has been caused by the last merge. 
Please update your instance.
Thanks for reporting 👍

**Comment by 1988luis** [comment]
cmd: ./crunz schedule:list
exception:
PHP Fatal error:  Cannot access protected property Crunz\Event::$command in /var/www/html/crunz/src/Console/Command/ScheduleListCommand.php on line 71

**Comment by lavary** [comment]
Same issue. Please update the package :)

**Comment by josealgardataborges** [comment]
root@hotspot1:~# crunz schedule:list

[BadMethodCallException]

schedule:list [<source>]

**Comment by josealgardataborges** [comment]
root@hotspot1:~# crunz schedule:run

[BadMethodCallException]

schedule:run [<source>]

**Comment by lavary** [comment]
@josealgardataborges would you please provide your task file?

**Comment by josealgardataborges** [comment]
Nevermind, it was a "typing error":

use Crunz\Schedule;

$scheduler = new Schedule();

$scheduler->run('/usr/bin/php')
          ->description('Task description')
          ->EveryMinute();


return $scheduler;


EveryMinute() should have been everyMinute()

**Comment by lavary** [comment]
@josealgardataborges 👍

**Comment by PabloKowalczyk** [comment]
@1988luis @josealgardataborges is issue still exists?

**Comment by josealgardataborges** [comment]
Hi @PabloKowalczyk as stated in my comment on 11 Aug 2016, it was a "Typo" on my code... Sorry for keeping this open so long ;)
