### ISSUE TITLE
Respect end of line in output logs?

### ISSUE THREAD

**Issue by kinoute** [lavary/crunz#186]
**Description**  
At the moment, when logging outputs to a file, if the output of a task consists of many lines, they all appear on a single line in the output log file. Wouldn't it better for readability to respect the end of line when logging the output?

**Example**  

test.php
```php
<?php

echo 'Started task...' . PHP_EOL;
echo 'Analyzing files...' . PHP_EOL;
echo 'Saving files...' . PHP_EOL;
echo 'Were done!' . PHP_EOL;
```

output log:
`[2019-01-24 15:55:38] crunz.INFO: Test(cd app/game/test; php test.php)   Started task... Analyzing files... Saving files... Were done!   [] []`

**Comment by PabloKowalczyk** [comment]
Hello, did you tried to set `log_allow_line_breaks: true` in your `crunz.yml`?

**Comment by kinoute** [comment]
Oops, I didn't have this option in my `crunz.yml` file..  I guess I have been using crunz for a very long time and this option wasn't available back in the days. Works like a charm now, thank you!
