### ISSUE TITLE
Symlink apparentley not created during install. Now what?

### ISSUE THREAD

**Issue by jamminjames** [lavary/crunz#195]
**Crunz version**: ^1.11

**PHP version**: 7.2

**Operating system type and version**: CentOS 7.2 with Nginx 1.9.15

**Description**  
I ran composer require lavary/crunz, and it was added to the composer.json file, and the files installed in /vendor just fine. 

I added the cronjob on the server:` * * * * * cd /var/www/subs.humortimes && vendor/bin/crunz schedule:run`

Under Installation it says: "If the installation is successful, a command-line utility named crunz is symlinked to vendor/bin directory of your project."

Apparently there is a problem with it, or something isn't working that is causing the class to not be found. (When I run the Task.php file from the browser, I get: "Fatal error: Uncaught Error: Class 'Crunz\Schedule' not found".)

I think it's the symlink, because in Filezilla, I can download another symlink and get a php file (I suppose it's the file that is symlinked to), but when I try that for crunz, it says there is no such file. 

How can I recreate the symlink, to rule out that as the cause? Thanks.

**Comment by jamminjames** [comment]
Okay, I just tried running `composer require lavary/crunz` again, and now the symlink appears to be okay. 

Then, I had to add `require_once __DIR__.'/../vendor/autoload.php';` at the top of the file, which while I should have known, it would be a good reminder to put that in the install instructions. I had to add the '/../' at the beginning since the Task.php file is in a subfolder (tasks).

I'm not getting any errors now when I run it from the browser, however, nothing is getting logged, and it seems the test jobs I have set up to run once a minute are not running.

**Comment by jamminjames** [comment]
I'd like to log errors to try and figure this out, but running `/vendor/bin/crunz publish:config` from the project root gives a 'no such file or directory' error.

Another problem is I am getting an error saying that this is not getting to the correct file:
`$schedule->run('../SubsPgsPHP/cron_pendingcount.php')`
...but /SubsPgsPHP is a parallel folder to /tasks, so I would think this would be correct.

**Comment by PabloKowalczyk** [comment]
Hello, Crunz is a CLI tool and it was never meant to be used from browser.
If you use Crunz by its "front controller" (binary file) it loads your project autoloader and there is no need to do it in every task.
Could you run `/vendor/bin/crunz publish:config -vvv` and paste the output of this command?

**Comment by jamminjames** [comment]
Yes, I realize it's not supposed to be run from the browser, however, I was not getting any feedback via logs, etc, so I did it to see if there were any php errors. It did help me figure out I had to add `require_once __DIR__.'/../vendor/autoload.php';`

The result of the command is "No such file or directory". I ran it from the project root, and /vendor/bin is definitely there, and when I check it out via Filezilla, crunz is showing, so I'm baffled.

**Comment by jamminjames** [comment]
Ok, error log says `sh: ../SubsPgsPHP/cron_pendingcount.php: No such file or directory`
But as I said earlier, that should be the correct path, since it's a parallel directory to the one Tasks.php is running from, yes? Should I give the path all the way from the server root?

**Comment by jamminjames** [comment]
Okay, I changed it to just `SubsPgsPHP/cron_pendingcount.php`, as if it's running from the source directory, and that seemed to work. I'm surprised it would accept that as the path. 

Anyway, new problem, it doesn't seem to be reading the php file as a php file, I am getting this error:

`[2019-02-12 21:52:01] crunz.ERROR: Continue emails daily until done, limited in number by renewalemail.php.(SubsPgsPHP/cron_pendingcount.php)  SubsPgsPHP/cron_pendingcount.php: line 1: ?php : No such file or directory SubsPgsPHP/cron_pendingcount.php: line 2: //: Is a directory SubsPgsPHP/cron_pendingcount.php: line 3: syntax error near unexpected token `'connectdb.php'' SubsPgsPHP/cron_pendingcount.php: line 3: `include_once('connectdb.php'); '   [] []`

So, the first line of the file I'm trying to run has "<?php" of course, since it's a php file. Yet scheduler seems to think I'm trying to name a directory. The next line is a commented line starting with "//" and again, it seems to  think I'm trying to name a directory. Why is it not running the file as a php script?

**Comment by jamminjames** [comment]
Ahhh, NOW I get it... didn't notice you had to put the path of the php binary in there. Got it working now. Thanks!!!
