### ISSUE TITLE
Questions: Do tasks all need to be named "$schedule" and how to list more than one? And more Qs.

### ISSUE THREAD

**Issue by jamminjames** [lavary/crunz#196]
**Crunz version**: 1.11.1

**PHP version**: 7.2

**Operating system type and version**: nginx on Centos 7

**Description**  
It seems only one "new $schedule" will run, it doesn't seem to be looking past the first one. How do I list more than one in a single Task.php file? Do they need to be named differently, ie, not all $schedule? 

When I put `return $schedule;` only at the end of the file, instead of after every task, it does seem to get through the whole file, however, it seems to only trigger the last job. (At least, that's the only one that gets output sent to a log file, although I have them all set to log to different files.) I have several set at one minute for testing, but only the last one runs.

Also, if you change the frequency of the cron job, will that change be picked up right away? I changed one from `->everyFiveMinutes()` to `->everyMinute()` and it doesn't seem to be picking that up.

**Comment by jamminjames** [comment]
Okay, got it. `$schedule = new Schedule();` only goes at the very top of the Tasks.php file, and `return $schedule;` only at the end of the file. Now all the jobs are running.

It would be good to make that clear in the install instructions, for less experienced folk like me. Thank you!

**Comment by PabloKowalczyk** [comment]
Hello, it is a good tip to inform user about files which do not return `Schedule` instance, i will implement it later.

**Comment by PabloKowalczyk** [comment]
Implemented and merged to `v1.12`, thanks @jamminjames for tip.
