### ISSUE TITLE
Passing variables to function

### ISSUE THREAD

**Issue by jamminjames** [lavary/crunz#197]
**Crunz version**: 1.11.1

**PHP version**: 7.2

**Operating system type and version**: nginx on Centos 7

**Description**  
Sorry for my learning curve here, with this being the third issue I've posted. Thanks for helping me figure it out.

Now my problem is how to pass a variable into the `->when(function()` to test against, and see if I want the cron to run.

I've accessed my db at the top of the Tasks.php file and set variables to the value of queries to the db, but I can't seem to get the function to read the variables. I've tried adding a "global" statement. 

Do I need to extend the class to do this? How would you recommend doing it?

Here's what I have so far:

```
require_once __DIR__.'/../vendor/autoload.php';

include_once __DIR__.'/../SubsPgsPHP/connectdb.php';
$sql="select cronjob,crontab,lastrenewid from control";
$rsc = mysqli_fetch_assoc( mysqli_query($db,$sql) );
$lastrenewid=$rsc["lastrenewid"];
global $lastrenewid;  // Putting this here and inside the function, not sure which is best

use Crunz\Schedule;
$schedule = new Schedule();

$schedule->run('/usr/bin/php SubsPgsPHP/renewalemail.php')
        ->everyMinute()
	->sendOutputTo('log/cron_finishemails.log')
	->description('Continue emails daily until done, limited in number by renewalemail.php.')
        ->when(function() {
		global $lastrenewid;
		if ($lastrenewid<>0) {
			return true; }
        });
```

Thanks for any help.

**Comment by jamminjames** [comment]
Update: Managed to get it working by moving the whole db block into the function, but it seems like doing something like this should work:
`->when(function() use ($lastrenewid) {`
... but I tried that and it didn't work. Is there any way to get that to work? An argument inside `function($arg)` perhaps?

It would be cleaner to keep the db query outside the function, so it could be used in other tasks as well.

**Comment by jamminjames** [comment]
Update: GOT IT! All I had to do was move the db block inside of the `$schedule = new Schedule();` line. Now `->when(function() use ($lastrenewid) {` successfully brings in the variable. It seems the closure can only get the variable from the parent function, not outside of that. Awesome!

**Comment by PabloKowalczyk** [comment]
Hello, there was similar case about passing variables to closures - https://github.com/lavary/crunz/issues/124.
Maybe it will be a better option to put DB logic in command not in task definition, but, of course, it depends :)

**Comment by jamminjames** [comment]
Well, if you want to use the variables in more than one task, it's best to do it the way I described, I think.
