### ISSUE TITLE
Can't get cron() to work correctly

### ISSUE THREAD

**Issue by jamminjames** [lavary/crunz#198]
**Crunz version**: 1.11.1

**PHP version**: 7.2

**Operating system type and version**: nginx

**Description**  
Can't get `->cron()` to work. I used `->cron('16 15 13 * *')`, which should have fired at 3:16pm today (13th), but didn't. I tried it several times, at different times, setting it a few minutes ahead. I know the server has the correct time.

**How to reproduce**  
I have a very similar task set up in the same file, using the same run() path, but with a `->everyFiveMinutes()` cron, and it is working fine. But this is not:
```
$schedule = new Schedule();
$schedule->run('/usr/bin/php SubsPgsPHP/renewalemail.php')
	->cron('16 15 13 * *')
	->sendOutputTo('log/cron_renewalemail.log')
	->description('Start a monthly renewal email, if cron enabled.');
```
Why would it not be working?

**Comment by jamminjames** [comment]
Yes, it is set correctly, to UTC - 8h, which is US Pacific Time. Could it be that it is taking the server's time and adding 8 hours to that?

**Comment by jamminjames** [comment]
Yup, that's it! Just tested it, and used a time 8 hours in advance, and it triggered it. So, I should set the UTC to 0.

**Comment by PabloKowalczyk** [comment]
Could you paste content of your `crunz.yml`?

**Comment by jamminjames** [comment]
All of it? Here it is, minus the commented out lines:

source: tasks
suffix: Tasks.php
timezone: UTC - 0h
log_errors: true
errors_log_file: /var/www/subs.humortimes/log/cron_errors.log
log_output: false
output_log_file: ~
log_allow_line_breaks: false
email_output: false
email_errors: false
mailer:
    # Possible values: smtp, mail, and sendmail
    transport: smtp
    recipients:
    sender_name:
    sender_email:

# SMTP settings
smtp:
    host: ~
    port: ~
    username: ~
    password: ~
    encryption: ~

**Comment by PabloKowalczyk** [comment]
Could you run Crunz with `-vvv` and paste the result?
IMO `timezone: UTC - 0h` is wrong value and Crunz ignores it, valid values for `timezone` are there https://secure.php.net/manual/en/timezones.php.

**Comment by jamminjames** [comment]
So, I should have it set like this?
timezone: America/Los_Angeles

**Comment by PabloKowalczyk** [comment]
Exactly. Again: could you run Crunz with `-vvv` and paste the result?

**Comment by jamminjames** [comment]
You mean run this?
/vendor/bin/crunz publish:config -vvv

**Comment by PabloKowalczyk** [comment]
I mean `vendor/bin/crunz schedule:run -vvv` - this should show which timezone was used.
