### ISSUE TITLE
Doesn't seem to detect the directory root

### ISSUE THREAD

**Issue by acelaya** [lavary/crunz#20]
I've started to play with this project, and the first stopper that I find is that it doesn't seem to properly detect the project root.

When I run any CLI command, it thinks the project root is inside vendor/lavary. That makes, for example the command make:task to create the file in vendor/lavary/tasks/fooTask.php, instead of tasks/fooTask.php
The same happens with the crunz.yaml config file. If I set something in the copy inside the project root, it doesn't take effect. However, it does If I change the file vendor/lavary/crunz.yml (which I think it has been created after running the publish:config command)

I'm running the commands from the project root, with `vendor/bin/crunz make:task`, but it seems to do the same if you change current dir to vendor/bin and run `crunz make:task`.

Also, the all commands throw lots of warnings until you create the crunz.yml file, because it is not able to open it.

```
PHP Warning:  file_get_contents(/home/user/crunz_test/vendor/lavary/crunz/src/Configuration/../crunz.yml): failed to open stream: No such file or directory in /home/user/crunz_test/vendor/lavary/crunz/src/Configuration/Configuration.php on line 62
```

**Comment by lavary** [comment]
This was due to one of the latest commits. I've fixed the issue for now.

Thanks a lot for reporting this.

**Comment by acelaya** [comment]
You are welcome

--
Alejandro Celaya Alastrué

**Comment by lavary** [comment]
I'll let you know when I create the release.

**Comment by lavary** [comment]
You may update the package: `v1.4.6`
