### ISSUE TITLE
Way to check when one job ran, make sure other job doesn't run before x time has passed

### ISSUE THREAD

**Issue by jamminjames** [lavary/crunz#200]
**Description**  

Don't know if there's a way to do this already or not, but I'd like to be able to check when one job ran before running a different one, and see if x amount of time has passed. Is this possible?

**Example**

**Comment by PabloKowalczyk** [comment]
Hello, currently it is not possible. It could be implemented to Crunz core, but it is beyond Crunz primary purpose. IMO it will be much better when you imeplement this logic in your own class/script/bin/whatever than rely on some 3rd party package.

**Comment by jamminjames** [comment]
Okay, thanks.
