### ISSUE TITLE
Complete list of Dynamic Methods?

### ISSUE THREAD

**Issue by jamminjames** [lavary/crunz#201]
**Description**  

Is there a complete list of Dynamic Methods somewhere? Is the following possible, for example?

```
->everyTwoWeeks()
->mondays()
->at('13:30');
```

... to run every other Monday at 1:30pm?

**Example**

**Comment by PabloKowalczyk** [comment]
Hello, there is no complete list of dynamic methods on Event class. `everyTwoWeeks` is not acceptable. You can use everything that match this pattern `/^every([A-Z][a-zA-Z]+)?(Minute|Hour|Day|Month)s?$/`.

**Comment by jamminjames** [comment]
Okay, thanks.

**Comment by PabloKowalczyk** [comment]
It will work and produce CRON exerpssion like this `0 0 */14 * *` - which means "At 00:00 on every 14th day-of-month.". Please note "**14th day-of-month**" is not "every 14 days". It may fit or may not, it depends on your needs.

**Comment by jamminjames** [comment]
That dynamic method is from an example given somewhere I saw. So why is it worded that way? Sure sounds like it will trigger every 14 days.

**Comment by jamminjames** [comment]
That dynamic method is from an example given somewhere I saw. So why is it worded that way? Sure makes it sound like it will trigger every 14 days.

**Comment by PabloKowalczyk** [comment]
I don't know why it is worded that way, but it definitely need to change to better inline with CRON.
Maybe i will deprecate it even in v1.12, otherwise in v2.0.

> So the only way to do twice a month would be: `0 0 1,15 * *` or some other two numbers, correct?

Correct.

**Comment by jamminjames** [comment]
Well, might be better to just explain that fact in your directions, rather than deprecate it. Thanks for your help, and your great program!
