### ISSUE TITLE
Task Life Time

### ISSUE THREAD

**Issue by fluchi** [lavary/crunz#205]
**Crunz version**: v1.11.1

**PHP version**: 7.1.18

**Operating system type and version**: Ubuntu - 17.10.1

**Description**  
Documentation says that we can specify tasks life time using either **from-to** or **between** methods.
After setting a task using this feature, I'm not quite sure that the process has a life time, based on the _list_ command.
Maybe, this is managed somehow within the library, really sorry if that's the case.

**How to reproduce**  
`<?php
//
$schedule->run('/usr/bin/php email.php')
         ->everyFiveMinutes()
         ->between('12:30', '04:55');

 //`
I've got */5 * * * * from tasks list, and it does not match with what I've set up.

thanks
Felipe

**Comment by PabloKowalczyk** [comment]
Hello, as said in documentation:

> In a crontab entry, we can not easily specify task's lifetime

This means that task lifetime is recognized on Crunz level, not Cron level. Cron expression `*/5 * * * *` is valid for this case. Did `between` doesn't work for you?

**Comment by fluchi** [comment]
Hi @PabloKowalczyk ,

I actually hadn't tested `between` feature before open the issue, sorry about that.
I've just made a quick test and it works.

Thanks

**Comment by PabloKowalczyk** [comment]
No problem :) Feel free to open new issue if `between` doesn't work for you.
