### ISSUE TITLE
Composer installs crunz executable to vendor/bin instead of symlink

### ISSUE THREAD

**Issue by MarkLittlewood** [lavary/crunz#207]
**Crunz version**: 1.11

**PHP version**: 7.1.17

Ubunto:

**Description**  
Crunz executable was installed by composer directly into vendor/bin instead of a symlink.
The $autoloadPaths then tried to go up 2 levels to find autoload.php but failed because executable was only 1 level down.

**How to reproduce**  
Not sure, local install of crunz created a symlink, install on server created executable

**Possible Solution**  
either add another option to $autoloadPaths that only looks one level of or find autoload.php in a way not dependant on how far down the tree it is?

**Additional context**

**Comment by MarkLittlewood** [comment]
Further investigation, it is not composer that is causing the issue. The application is packaged up and it is that process which is converting the symlinks. The net result though is that the crunz executable is in vendor/bin rather than the symlink and so is failing to find autoload.php

**Comment by PabloKowalczyk** [comment]
Hello, what you mean by "application is packaged up"?

> crunz executable is in vendor/bin

Looks like another autoloader possible path `__DIR__  . '/../auotload.php'` should do the trick?

BTW I'm wondering why Composer choose to create hard copy instead of symlink, maybe your filesystem on server doesn't support symlinks?

**Comment by MarkLittlewood** [comment]
Hi we use are using zs-client,  a feature of zend server for deployments which "packages up" the application and deploys it.

I think that the additional autoloader possible path should solve the issue.,

Thanks

**Comment by PabloKowalczyk** [comment]
> Hi we use are using zs-client, a feature of zend server for deployments which "packages up" the application and deploys it.

Everything is clear now.

> I think that the additional autoloader possible path should solve the issue.,

Would you like to provide a PR for `1.11.x` branch?

**Comment by MarkLittlewood** [comment]
Pr created. Thankyou

**Comment by PabloKowalczyk** [comment]
Let's wait with "close" to PR merge.

**Comment by MarkLittlewood** [comment]
I create a branch with the change, but when I try and push it I get:
remote: Permission to lavary/crunz.git denied to MarkLittlewood.

**Comment by PabloKowalczyk** [comment]
Fixed in #209 (and in #210) and released in `v1.11.2`, thanks @MarkLittlewood.
