### ISSUE TITLE
Running Task On Windows

### ISSUE THREAD

**Issue by MyNameIsPedram** [lavary/crunz#215]
Hello.

For Example, I have a file called Hello.php.

Hello.php Contents :
file_put_contents('some.txt','Hello');

Now, I Want To execution this file on eg: december 2020.

in the "Windows with Xampp", How Can i execution This Task ? 

Thanks.

**Comment by PabloKowalczyk** [comment]
Hello,

would you like to setup Crunz on Windows or just run some command once at given time?

**Comment by MyNameIsPedram** [comment]
Yes, just run some command..

**Comment by PabloKowalczyk** [comment]
So if i understand correctly you don't need Crunz?

**Comment by MyNameIsPedram** [comment]
no deffrent, i just run task, see attachment. i want to know how to run this task on windows.
[Uploading cron.zip…]()

**Comment by MyNameIsPedram** [comment]
look, i say transparent.

Here is my Code:

```
`<?php

if(isset($_POST['submit'])) {
		
	$cmd = 'ffmpeg .......';
	
	shell_exec($cmd):

	exit;
}


?>

<form method="POST">
	<input type="submit" name="submit">
</form>`
```

When the user submit the form, it takes 5 minutes for the shell to execute the command to complete the request.

Instead of waiting for this, I want to make the  shell operation Run 5 minutes later.

**Comment by PabloKowalczyk** [comment]
I see now, you need async processing, something like RabbitMQ or even Redis' pub/sub should do the job.
IMO Crunz can't help you, it is design to run jobs periodically, just like Cron in Linux.
