### ISSUE TITLE
Output information about failed task when log_errors is disabled

### ISSUE THREAD

**Issue by downace** [lavary/crunz#219]
**Description**

When task ends with non-zero exit code, its output is forwarded to console and there is no additional information. It would be nice to see at least `Crunz\Event::buildCommand()` result (like in log file when `log_errors: true`).

Or maybe its better just not to ignore the output of `errorCallbacks`, so developer can output anything they need there. Currently output is ignored (`vendor/lavary/crunz/src/EventRunner.php:180`, v1.11.2).

**Example**

Task fails with exhausted memory limit, it outputs something like this:

```
PHP Fatal error:  Allowed memory size of 20971520 bytes exhausted (tried to allocate 33554440 bytes) in db.php on line 5
```

The `db.php` file may be used in almost every scheduled task, so it's impossible to tell which task is failed.

Such errors are not capturable (AFAIK) and xdebug is not always available in production environment, so stack trace is not available too.

`register_shutdown_function` can be used as a workaround:

```php
// ...
$error = '';

$schedule->onError(function(\Crunz\Event $evt) use (&$error) {
    $error .= $evt->getExpression() . ' ' . $evt->buildCommand() . PHP_EOL;
});

register_shutdown_function(function() use (&$error) {
    if ($error) {
        echo PHP_EOL . $error . PHP_EOL;
    }
});
```

**Comment by PabloKowalczyk** [comment]
Hello, could you run `crunz schedule:run -vvv`? Some useful information will be shown, but i don't know this will satisfy you?
Few versions ago i changed the way how `EventRunner` handles output from tasks, everything from `stdout` and `stderr` should go to console when `log_errors` is `false` - maybe you disabled displaying errors in your `php.ini`?

**Comment by downace** [comment]
Hello!

I should have explained my use case. I use a separate script to capture errors which are not captured inside a task itself (e.g. memory limit exhaustion). This script considers any output from `crunz schedule:run` as error and reports it to issue tracker. Maybe it should capture only `stderr`, but `crunz` passes all output to `stdout`, so it's not possible to separate errors from normal output, that's why `-vvv` is not suitable because it will produce output even when there are no errors.

> maybe you disabled displaying errors in your `php.ini`

```
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
```

Error is displayed, but without a stack trace (AFAIK, xdebug is required for this, which is not recommended for production environment), thus error message is often useless: memory exhaustion may occur anywhere (e.g. in database connection class).

Maybe this use case is very specific and `crunz` developers should not consider it, because in most cases errors are logged or emailed. But I think that output of `onError` and `after` (`then`) callbacks should not be ignored. BTW, the output of `after` callback of `Event` (not `Schedule`) is not ignored, it looks a little inconsistent for me. Maybe I'm missing something...

**Comment by PabloKowalczyk** [comment]
Symfony shows full stack traces even without XDebug so it is doable.

With below config `Crunz` will write output to `stderr`, but only on error:
```
# crunz.yml
log_errors: true
errors_log_file: php://stderr
```
Does it help?

**Comment by downace** [comment]
> Symfony shows full stack traces even without XDebug so it is doable.

..but not for non-capturable errors, like memory exhaustion. This is the main problem, all capturable errors are captured and reported inside script itself.

<details>
<summary>Test</summary>



```bash
composer require lavary/crunz symfony/console
vendor/bin/crunz config:publish
```

`tasks/AllTasks.php`:

```php
<?php
require_once __DIR__ . '/../vendor/autoload.php';
$schedule = new \Crunz\Schedule();
$schedule->run('php -d memory_limit=5M script.php foo -vvv')
    ->everyMinute();
return $schedule;
```

`script.php`:

```php
<?php
namespace App;
require_once __DIR__ . '/vendor/autoload.php';
use Symfony\Component\Console\Application;
$app = new Application();
$app->register('foo')->setCode(function() {
    $a = \array_fill(0, 100000, 1);
    return 0;
});
$app->run();
```

`vendor/bin/crunz schedule:run`

```
PHP Fatal error:  Allowed memory size of 5242880 bytes exhausted (tried to allocate 4194312 bytes) in /root/script.php on line 12
```

`vendor/bin/crunz schedule:run -vvv`:

```
Using config file /root/crunz.yml.
Task source path '/root/tasks'
Realpath for '/root/tasks' is '/root/tasks'
Task finder pattern '/root/tasks/*Tasks.php'
Found 1 task(s) at path '/root/tasks'
Timezone from config: 'Asia/Yakutsk'.
Timezone for comparisons: 'Asia/Yakutsk'.
Invoke Schedule's ping before
There is no ping before url.
Invoke Event's ping before.
There is no ping before url.
PHP Fatal error:  Allowed memory size of 5242880 bytes exhausted (tried to allocate 4194312 bytes) in /root/script.php on line 12
Task crunz5caef0d1970e67.60290658 status: fail.
Invoke Schedule's ping after.
There is no ping after url.
```

</details>

> With below config Crunz will write output to stderr, but only on error:
> 
>     # crunz.yml
>     log_errors: true
>     errors_log_file: php://stderr
>
> Does it help?

This works, thanks! The error now looks like this:

```
[2019-04-11 16:49:06] crunz.ERROR: (php -d memory_limit=5M script.php foo -vvv)  PHP Fatal error:  Allowed memory size of 5242880 bytes exhausted (tried to allocate 4194312 bytes) in /root/script.php on line 12   [] []
```

But it looks like a hack, not like a normal solution, IMO...

Anyway, solution is found, so you can close this if there are no plans to consider any of my suggestions.

Thanks!

**Comment by PabloKowalczyk** [comment]
IMO it is not hack, you just configure `Crunz` (`Monolog` actually) to write to `stderr` on error and it is completely valid from `Monolog` and `Crunz` point of view.

Thanks @downace.
