### ISSUE TITLE
Similar package. Collaborate?

### ISSUE THREAD

**Issue by chrismichaels84** [lavary/crunz#22]
Aloha! I created a similar package for my company (which we use in production hundreds of times a day), and recently posted it to github. I had intended to expand and clean it up.

We seem to be trying to solve a lot of the same problems, and each have features the other package doesn't. Would it be worth looking through my library and collaborating? I'd be happy to merge my work over to your library where appropriate.

My package is at https://github.com/chrismichaels84/mistletoe. It is fully PSR compliant, well tested, and build on SOLID principles.

Some features include:
- Simplify ALL cronjobs into a single job
- Environment detection and limiting (only run certain tasks in production)
- Tasks may be console commands, classes, or callables
- Fluent cron schedule builder
- An included TaskRunner
- Easy to create custom task runners
- A working phar

Some things it may have to offer are:
- [ ] Transforming cron expressions into natural language expressions
- [ ] Creating TaskRunners
- [ ] Run tasks in sequence (one followed by two followed by three)
- [ ] Environment detection so you can run some on production and other on development 

Just a thought.

**Comment by lavary** [comment]
Hey Michael. I apologize for the extremely late reply. 
I think that's a very good idea. Crunz is very young and there's a lot of room for improvement. It's a good idea to centralize future contributions on one sole library. I'll take a look at your code to see how we can collaborate. Would you please do the same? 

Cheers.

**Comment by chrismichaels84** [comment]
Absolutely. I'll try to get to it this week. Works a little crazy with an
upcoming deployment

**Comment by lavary** [comment]
👍

**Comment by chrismichaels84** [comment]
Things have calmed down a bit for me. Did you see any features/parts you would like to integrate?
