### ISSUE TITLE
Tasks Subdirectories

### ISSUE THREAD

**Issue by rrushton** [lavary/crunz#228]
**Crunz version**: 1.12.0
**PHP version**: 7.1.25

In crunz.yml I have set the source: src/tasks
In my src/tasks directory if I place a file name TestTasks.php and run schedule:list it shows the item but if I create a subdirectory called Test and place TestTasks.php in there schedule:list shows no tasks.

I see in the readme it states "Since Crunz scans the tasks directory recursively..." so I assumed it would look in subdirectories. Should it be scanning subdirectories?

Thanks.

**Comment by PabloKowalczyk** [comment]
Hello,
yes, it should scan sub directories. Probably i removed recursive scan by accident, it is a bug and i will fix it in `v1.12` branch.

**Comment by PabloKowalczyk** [comment]
@rrushton could you test that patch https://github.com/PabloKowalczyk/crunz/tree/fix-recursive-tasks-scan?

**Comment by rrushton** [comment]
@PabloKowalczyk running schedule:list now shows the Tasks file in the sub directory. Thanks for looking into this so quickly.

**Comment by PabloKowalczyk** [comment]
Fixed in #229 and released as `v1.12.1`, thanks @rrushton.
