### ISSUE TITLE
Question: Which locking mechanism should be the preferred one?

### ISSUE THREAD

**Issue by halukpp** [lavary/crunz#234]
Would you suggest using the default file based locking or symfony/lock as best practice?

**Comment by PabloKowalczyk** [comment]
Hello, default lock store for current (stable, v1.12.x and v2.x) versions of Crunz is `\Symfony\Component\Lock\Store\FlockStore`, so under the hood it is always `symfony/lock`, old Crunz's locking was removed.
IMO you could use file/sempahore locking if you run only one Crunz instance, but if you have multiple instances you should use one of distributed ("remote" - PDO/MongoDB/Redis/etc.) store to make sure all instances will respect locks.
Available stores: https://symfony.com/doc/current/components/lock.html#available-stores

**Comment by halukpp** [comment]
This is good information. 

We are currently using v1.11.*
On one server we are managing about 200+ cron tasks using Crunz.

Recently we had some issues with locking but couldn't really find the root cause.
Now we are checking daily to see if the lock problem repeats itself.

In the meantime probably we'll switch to 1.12.x and keep this information in mind.

Appreciate the time you took for this message.

**Comment by PabloKowalczyk** [comment]
I have checked again source of `v1.11` and it should behave like `v1.12`. Maybe there is a bug in Crunz or Symfony's lock component. Please upgrade your Crunz to `v1.12` first and if bug still exist please open new issue, i will try to help.
