### ISSUE TITLE
Crunz uses a deprecated fork of a package

### ISSUE THREAD

**Issue by mareksuscak** [lavary/crunz#239]
**Description**  

Crunz depends on the following library:
https://github.com/mtdowling/cron-expression

This is a fork of a different library which has been deprecated. We should consider pointing it to https://github.com/dragonmantank/cron-expression

**Comment by PabloKowalczyk** [comment]
Hello, you are right `mtdowling/cron-expression` is deprecated and no longer maintained, but does this package harm your project/use-case in any way?

**Comment by mareksuscak** [comment]
Nope. Nevertheless, it would be great if crunz (and any widely used package really) depended on supported packages only. 

Moreover since the former is a fork of the latter, switching to the upstream should be easy for the APIs seem to be compatible.

What do you think?

**Comment by PabloKowalczyk** [comment]
> Nevertheless, it would be great if crunz (and any widely used package really) depended on supported packages only.

100% agree, i was just curious.

If libraries switch can be done without any BC break, it could go even for next minor version (`v2.1`), would you like to provide a PR?

**Comment by mareksuscak** [comment]
Well just to give you a little bit of a backstory what motivated me to file this issue — we have a job that is supposed to run on 4th day, every month but it was started multiple times yesterday (which as it turned out was a bug in our schedule definition) but then this morning it was started again and I haven't been able to explain why. I'm not sure if this library has to do anything with that or not. Hence why I did not mention it in my comments above.

**Comment by PabloKowalczyk** [comment]
So, maybe there are bug in Crunz itself? Could you reproduce behavior in clean repository?

**Comment by mareksuscak** [comment]
So we had a conversation w/ the team and by looking at the email submission times, it seems that the job wasn't executed this morning as we initially thought but late at night yesterday (since our scheduler uses UTC timezone and if we adjust for the offset it would explain the situation). So it's not related to this issue. But this issue is relevant regardless in my opinion.

**Comment by PabloKowalczyk** [comment]
Agreed, would you like to provide a PR?

**Comment by mareksuscak** [comment]
@PabloKowalczyk yup. Will do.

**Comment by PabloKowalczyk** [comment]
Fixed by #240.
