### ISSUE TITLE
How to run/test specific task?

### ISSUE THREAD

**Issue by devudopw** [lavary/crunz#242]
I see the code has an option to run a specific task with these command
`vendor/bin/crunz schedule:run --task 1 --force`
But it seems not work?
I run the command, and all tasks executed.

**Comment by PabloKowalczyk** [comment]
Hello @devudopw, which versions of PHP, Crunz and OS are you using?

> I run the command, and all tasks executed.

Could you paste your php file behind `#1` task?
Also what is result of `vendor/bin/crunz schedule:list`?

**Comment by devudopw** [comment]
Hello @PabloKowalczyk 

under PHP 7.3.8:
> ~ # ./vendor/bin/crunz s:l
+---+--------------------------------+--------------+-----------------+
| # | Task                           | Expression   | Command to Run  |
+---+--------------------------------+--------------+-----------------+
| 1 | trigger update           | */30 * * * * | object(Closure) |
| 2 | trigger log | 0 0 * * *    | object(Closure) |
+---+--------------------------------+--------------+-----------------+

code from `#1` task:
```
<?php
declare(strict_types=1);
use Crunz\Schedule;

$scheduler = new Schedule();
$task = $scheduler->run(function() {
        echo file_get_contents('http://run');
});
$task
    ->description('trigger update')
    ->preventOverlapping()
    ->everyThirtyMinutes();
;

return $scheduler;
```

**Comment by PabloKowalczyk** [comment]
Probably I have reproduce your issue, could tell what version of Crunz you are using?

**Comment by devudopw** [comment]
I guess this is the version?
`vendor/bin/crunz -V`
Crunz Command Line Interface v2.0.1

**Comment by PabloKowalczyk** [comment]
It is version, thanks. Actually i found out that `require`d task file overwrite `$task` variable in `\Crunz\Console\Command\ScheduleRunCommand` class. Interesting bug, thanks for your report :)
PR in progress, as a quick fix you can change `$task` to something else in your task files.

**Comment by devudopw** [comment]
Glad that help.

**Comment by PabloKowalczyk** [comment]
#243 was merged, thanks @devudopw.
