### ISSUE TITLE
Write log/error to database

### ISSUE THREAD

**Issue by nvloi** [lavary/crunz#247]
Hi
I begin using Crunz in Zend Framwork and I want to receive log/error and write it to database. Can you tell me if there is a way to do it?
Thanks

**Comment by PabloKowalczyk** [comment]
Hello,
i think this can be easy after #216 is implemented, would you like to help or even provide a PR?

**Comment by PabloKowalczyk** [comment]
Fixed by https://github.com/lavary/crunz/pull/298.
