### ISSUE TITLE
Run multiple schedules per task file

### ISSUE THREAD

**Issue by davidsneighbour** [lavary/crunz#248]
**Description**  
It would be a nice feature to have multiple schedules enabled per Task file. The documentation does not imply this is possible now and the `return $schedule` at the end of a task file implies that too. 

**Example**  
I want to enable the setup of cronjobs in a database based system. Users would create tasks and set timing options. A file then would read the DB contents (runtimes, command) and create schedules for that. 

Is this possible with the current functionality?

Note: the request is about the adding of schedules, not the logic behind user created tasks and the db setup.

**Comment by PabloKowalczyk** [comment]
Hi,
is this issue https://github.com/lavary/crunz/issues/144 similar to your case? Look at https://github.com/lavary/crunz/issues/144#issuecomment-426368228 as a reference.

**Comment by davidsneighbour** [comment]
This explanation solves my issue.
