### ISSUE TITLE
Dynamic file names for error and event logs

### ISSUE THREAD

**Issue by davidsneighbour** [lavary/crunz#249]
**Description**  
It would be nice to be able to define dynamic filenames for error and cronjob logs like `cronjob-error-{$Ymd}.log`

Or, in extension to what might be needed to implement #247, it might be in general nice, to be able to add a generic error handler, so that we can add for instance a Monolog handler to receive everything Crunz outputs.

**Comment by davidsneighbour** [comment]
I just saw #216 - that would solve this issue I think.

**Comment by PabloKowalczyk** [comment]
Would you like to provide a PR for #216?

**Comment by davidsneighbour** [comment]
I can have a look into it, but I might have additional questions. I'll let you know in a bit.

**Comment by PabloKowalczyk** [comment]
Fixed by https://github.com/lavary/crunz/pull/298.
