### ISSUE TITLE
between --> Documentation / Functionailty example

### ISSUE THREAD

**Issue by simmonspaul** [lavary/crunz#254]
I think if the document had some further examples that it would assist other users. 

I wanted to use the "between" option to have some of my jobs only run during certain times
->between('04:05', '04:15')

However I wanted this to be the same for each hour. 
Effectively a range of times that my job would run each hour.
This would help organise competing tasks and assist in tuning performance.

I tried to add multiple "betweens" and it did not work.
 ->between('05:05', '05:15')
->between('06:05', '06:15')
...
 ->between('18:05', '18:15')

I couldn't think of how to do a "between" "minutes" or otherwise specify an ok to run range.

The way that I achieved what I was trying to do was:
 $hour = date('H');
 $start = $hour.':05';
 $end = $hour.':15'; 

-> between($start,$end)

I hope this scenario and use helps someone else.

**Comment by PabloKowalczyk** [comment]
I believe you could achieve the same using plain cron expression `10-15 * * * *`, maybe would you like to extend documentation with your example? Would you provide a PR?

**Comment by simmonspaul** [comment]
Pablo, You are right. That is the way that is would be achieved using a cron expression.
Instead of between(), it could also be better achieved using ->minute('10-15').

Nonetheless, I was trying to get my head around the documentation and this PR has attempted to reorder things slightly to allow the examples to build on themselves more. This is purely my point of view and others might disagree.

This is my first time playing with github, so apologies if I have messed up the PR in the first case.

**Comment by PabloKowalczyk** [comment]
> This is my first time playing with github, so apologies if I have messed up the PR in the first case.

Everything was fine :smile: PR  #255 was merged, thanks @simmonspaul.
