### ISSUE TITLE
Monolog 2 Support

### ISSUE THREAD

**Issue by esetnik** [lavary/crunz#257]
https://github.com/lavary/crunz/issues/78

**Comment by davidsneighbour** [comment]
It's a bit weird to open a new issue referencing just an old issue. You didn't even take the time to reference the most advanced issue on this. Have a look at https://github.com/lavary/crunz/issues/216

Feel free to open a pull request. It seems not too complicated to implement this if one has time and the right understanding of how Monolog needs to be added.

**Comment by davidsneighbour** [comment]
https://github.com/lavary/crunz/issues/247 too is in this realm.

**Comment by esetnik** [comment]
Sorry about that. In the previous issue I linked it was suggested that a new issue be opened once monolog 2 is released so that's what I did. I didn't think it warranted any further discussion, but that was my mistake.
> There is no further answers from author, also date of release of Monolog v2 is not known so i will close this issue. Feel free to open new issue when Monolog will be v2 :)

**Comment by davidsneighbour** [comment]
Not a mistake... Let's get this one rolling :) I think it will be a great addition. Someone "just" needs to start on it. I am not too sure if it could be me.

**Comment by PabloKowalczyk** [comment]
Hello guys, actually i have idea to let users' configure logger, by allowing to specify `LoggerFactory` which will return PSR-3 instance, so any logger compatible with PSR-3 will be supported. I will create RFC soon and all the details will be discussed.

**Comment by PabloKowalczyk** [comment]
RFC was created (https://github.com/lavary/crunz/issues/259), I encourage you to discuss :smile:

**Comment by PabloKowalczyk** [comment]
Fixed by https://github.com/lavary/crunz/pull/298.
