### ISSUE TITLE
Not able to access dynamic Variable in the Scheduler when included from files

### ISSUE THREAD

**Issue by rahul9222** [lavary/crunz#258]
**Crunz version**: v1.12.2

**PHP version**: 5.6 and 7.3.10

**Operating system type and version**: AWS EC2 instance (CentOS)

**Description**  
Dynamic array value for the domain name is not accessible in PHP included file.

**How to reproduce**  
We have a Constant file for global value. Named as **CONSTANT.php**
```
$http = 'https://';
    $SITE_URL = array(
        'Hello' => 'hello.test.com',
        'World' => 'world.test.com'
);
```

And in the Crunz Task file the above file is included.

```

use Crunz\Schedule;

include_once('CONSTANT.php');

$schedule = new Schedule();

foreach ($SITE_URL as $key => $value) {
	$schedule->run('/usr/bin/curl '.$http.$value.'/cron/mailsend.php')
			->cron('0 0 * * 0')
			->preventOverlapping()
			->description('Send mail in Queue '.$key);
}

$schedule->onError(function() {
      // mail
});

return $schedule;
```

Tried with **php ./vendor/bin/crunz schedule:list** command.

Give the Error of 
**PHP Notice:  Undefined variable: SITE_URL in /var/www/test/tasks/EmailTasks.php on line 6**

Not able to access the **SITE_URL** variable in the latest version.

**Possible Solution**  
It properly worked on Crunz **v1.4.0**
But after the update, it failed to send email to the client.
While debugging found the above issue **need help**

**Comment by PabloKowalczyk** [comment]
Hello, did you try to use absolute path, like `include_once(__DIR__ . DIRECTORY_SEPARATOR . 'CONSTANT.php');`?

**Comment by rahul9222** [comment]
> Hello, did you try to use absolute path, like `include_once(__DIR__ . DIRECTORY_SEPARATOR . 'CONSTANT.php');`?

I tried by adding the absolute path, but it didn't work.

**Comment by PabloKowalczyk** [comment]
Could you create repository with code to reproduce the issue?

**Comment by rahul9222** [comment]
Yes, creating a repository at https://github.com/rahul9222/crunzissue

Some point that I observed that the **include_once()** only work for the first task file and then it doesn't work for the next task file.
And give the error **Undefined variable: SITE_URL**

![Issue captured](https://user-images.githubusercontent.com/16019891/67633137-04459380-f8d2-11e9-9f51-96855232745e.PNG)

**Comment by rahul9222** [comment]
Not sure what was the issue but it fixed by changing the **include_once()** to **include()** in every Tasks.php files.

![image](https://user-images.githubusercontent.com/16019891/67768298-3d1f6d00-fa78-11e9-9495-8ab083750114.png)

**Comment by PabloKowalczyk** [comment]
But, `include_once` works with Crunz `v1.4`?

**Comment by rahul9222** [comment]
> But, `include_once` works with Crunz `v1.4`?

Yes, it was working in the previous version

**Comment by PabloKowalczyk** [comment]
I found out what happening. In https://github.com/lavary/crunz/pull/243 I changed how tasks are loaded to avoid variable names registering/collisions/overriding (discovered in this issue: https://github.com/lavary/crunz/issues/242), so your code with `include_once` shouldn't work at all (sorry :smile:), but due to Crunz bug everything was working as expected, because variables from your include file was in Crunz's memory. Release `v1.12.2` fixed buggy behavior and also reveals bug in your code.
IMO it is not a BC break on Crunz side, you should use `include`, or even `require`, instead of `include_once` and everything will be fine.

**Comment by rahul9222** [comment]
Yes, it fixed after using the `include()` instead of `include_once()`.

Thanks
