### ISSUE TITLE
[RFC] LoggerFactoryInterface 

### ISSUE THREAD

**Issue by PabloKowalczyk** [lavary/crunz#259]
**Description**  
To address some of last requests (#257, #249, #247 and #216) users should be able to provide logger instance used by Crunz, the idea is to let users use any PSR-3 compatible logger by returning it from configured `logger_factory`. This means new configuration option will be added to allow specifying `LoggerFactoryInterface`.
Example below shows simple file logging by Monolog but there can be Zend Db logging used instead, every PSR-3 class will work.
By default Crunz will provide same file logging as before.

**Example**  

Interface itself:
```php
use Psr\Logger\LoggerInterface;

interface LoggerFactoryInterface
{
    public function createLogger(array $crunzConfiguration): LoggerInterface;
}
```

Example implementation:
```php
use Monolog\Logger;
use Monolog\Handler\StreamHandler;

class MonologLoggerFactory implements LoggerFactoryInterface
{
    public function createLogger(array $crunzConfiguration): LoggerInterface
    {
        $log = new Logger('name');
        $log->pushHandler(new StreamHandler('path/to/your.log', Logger::WARNING));

        return $log;
    }
}
```

Crunz configuration (`crunz.yml`):
```yml
# Class loadable by autloader
logger_factory: '\Vendor\MonologLoggerFactory'
```

**Comment by davidsneighbour** [comment]
Perfect. For my use case (#249) the perfect solution.  

Question: (I don't need this but it might come up) Does this give this logger instance exclusively to Crunz or can it be shared with other scripts that are logging? I wonder if there are any implications if I, for instance, let `createLogger` return my global logging instance as a clone and then those two are blocking each other for instance in file access?

**Comment by PabloKowalczyk** [comment]
> Does this give this logger instance exclusively to Crunz or can it be shared with other scripts that are logging?

IMO it depends on implementation of logger itself, for 99% it is safe to share logger instance.

**Comment by esetnik** [comment]
This looks great to me too. For my use-case it would be ideal if the logger instance could be made available to the closure itself. For example:

```php
<?php

use Crunz\Schedule;

$schedule = new Schedule();

$x = 12;
$task = $schedule->run(function($logger) use ($x) { 
   // Do some cool stuff in here 
   $logger->debug('closure running');
});

$task
    ->everyMinute()
    ->description('Copying the project directory');

return $schedule;
```

**Comment by esetnik** [comment]
And it might be better if the logger name and details can be configured for each task rather than globally from a single `crunz.yml`. I currently run several tasks and I'd want to have separate logger names for each.

**Comment by PabloKowalczyk** [comment]
> For my use-case it would be ideal if the logger instance could be made available to the closure itself.

It is a possible way to improve logging in the future, but now it is not in scope of this RFC.

> And it might be better if the logger name and details can be configured for each task rather than globally from a single crunz.yml.

IMO both options can, and should, coexist. For simple use cases users will just use global logging but for important/complex/etc use-case, special logger instance can be configured for just one task. This option deserves another RFC.

**Comment by PabloKowalczyk** [comment]
It took a while to implement this RFC but here it is: https://github.com/lavary/crunz/pull/298 - I encourage everyone to test it before merge.

Ping @jasonmccreary

**Comment by PabloKowalczyk** [comment]
#298 was merged.
