### ISSUE TITLE
preventOverlapping  is not work

### ISSUE THREAD

**Issue by ultralamer** [lavary/crunz#26]
preventOverlapping  is not work since commit cabc7a0363096ff1987173dc5968a23e9a66c8ae (Create an event runner with closure call support )

Event::lock() newer called and have incorrect code: undefined variable $event

**Comment by PabloKowalczyk** [comment]
Hello, do you still face this issue?

**Comment by ultralamer** [comment]
Hello! Unfortunately, i don't use crunz anymore.

**Comment by PabloKowalczyk** [comment]
So i will close this issue. Thanks.
