### ISSUE TITLE
Symfony\Component\Process\Process::inheritEnvironmentVariables() method is deprecated since Symfony 4.4

### ISSUE THREAD

**Issue by esetnik** [lavary/crunz#267]
**Crunz version**: x.y.z
v2.0.3
**PHP version**: x.y.z
v7.3.12
**Operating system type and version**:
linux
**Description**  
When running the job using Symphony v4.4 or greater a deprecation warning is logged to the console:
```
 [Deprecation] The
               "Symfony\Component\Process\Process::inheritEnvironmentVariables()
               " method is deprecated since Symfony 4.4, env variables are
               always inherited. File
               /usr/src/app/src/vendor/symfony/process/Process.php, line 1224
```

**How to reproduce**  
Run any lavary/crunz job

**Possible Solution**  
https://github.com/lavary/crunz/blob/master/src/Process/Process.php#L77
This check should be made more robust to check whether symphony 4.4 or greater is in use.

**Additional context**  

https://github.com/symfony/symfony/pull/32475

**Comment by esetnik** [comment]
@PabloKowalczyk I noticed this is also the cause of failing tests on master. See https://travis-ci.org/lavary/crunz/jobs/618324969#L342

**Comment by PabloKowalczyk** [comment]
@esetnik Yes, i know it, but currently I don't have time to fix it. Deprecation free code is also needed before #265 fix. PR is very welcome.

**Comment by PabloKowalczyk** [comment]
Fixed by https://github.com/lavary/crunz/pull/268
