### ISSUE TITLE
Stopped working, can't figure out why

### ISSUE THREAD

**Issue by jamminjames** [lavary/crunz#284]
**Crunz version**: x.y.z
2.1.0
**PHP version**: x.y.z
7.3
**Operating system type and version**:
CentOS 7.2 with Nginx/1.17.5
**Description**  

Nothing is happening with Task files.
**How to reproduce**  

I'm working with a very simple test file now, detailed below. It should trigger an email with the current time, but nothing happens. 

I've checked everything I can think of: file permissions, the cron job (works if I call a php file directly), updated composer (which updated crunz), etc. I set crunz.yml to log errors, but am getting none. I know the php bin file is correct (/usr/bin/php). 

The crontab I'm using is: `* * * * * cd /var/www/subs.humortimes && vendor/bin/crunz schedule:run >/dev/null 2>&1`

The Task file reads:
```
require_once __DIR__.'/../vendor/autoload.php';

use Crunz\Schedule;
$schedule = new Schedule();

$schedule->run('/usr/bin/php z_test_cron.php')
	->cron('30 16 * * *')
	->sendOutputTo('log/cron_renewalemail.log') // or appendOutputTo to append
	->description('Start a monthly renewal email, if cron enabled.');

$schedule->run('/usr/bin/php z_test_cron.php')
	->everyMinute()
	->sendOutputTo('log/cron_finishemails.log')
	->description('Continue emails daily until done, limited in number by renewalemail.php.');

$schedule->run('/usr/bin/php z_test_cron.php')
	->everyFiveMinutes()
	->sendOutputTo('log/cron_pendingcount.log')
	->description('Pending accounts change notice.');

return $schedule;
```
Although I have them each set to log to files (which are all writable), they do not. The "Z_test_cron.php" file never runs.

I can find nothing in my server error logs that is relevant.
**Possible Solution**  

I tried removing the crunz package and dependencies via composer and reinstalling, no change. (Although the "installing" notices for each item said "Loading from cache".)
Tried everything I can think of, at wits end. Any help would be appreciated! Thanks.
**Additional context**

**Comment by PabloKowalczyk** [comment]
Hello, could you show output from `vendor/bin/crunz schedule:run -vvv` command?

**Comment by jamminjames** [comment]
Here you go:

Using config file /var/www/subs.humortimes/crunz.yml.
Task source path '/var/www/subs.humortimes/tasks'
Task finder suffix: 'Tasks.php'
Realpath for '/var/www/subs.humortimes/tasks' is '/var/www/subs.humortimes/tasks'
Found 1 task(s) at path '/var/www/subs.humortimes/tasks'
Start file.<br>Ran 3rd Schedule.<br>Timezone from config: 'America/Los_Angeles'.
Timezone for comparisons: 'America/Los_Angeles'.
Invoke Schedule's ping before
There is no ping before url.
Invoke Event's ping before.
There is no ping before url.
Invoke Event's ping before.
There is no ping before url.
Invoke Event's ping after.
There is no ping after url.
Task Continue emails daily until done, limited in number by renewalemail.php. status: success.
Invoke Event's ping after.
There is no ping after url.
Task Pending accounts change notice. status: success.
Invoke Schedule's ping after.
There is no ping after url.

It resulted in the file being run, so now I'm really confused. I know the cron is working, having tried it on another php file, but it doesn't seem to be triggering the Task file.

Thanks for your help!

**Comment by jamminjames** [comment]
Well, now everything seems to be working again. It's as if the -vvv command woke it up! Strange.

**Comment by PabloKowalczyk** [comment]
It is weird, you should check your cron daemon logs for more information and removing ` >/dev/null 2>&1` will help with debugging.
