### ISSUE TITLE
onOneServer

### ISSUE THREAD

**Issue by MarcosGrzeca** [lavary/crunz#289]
**Description**  
An option to indicate that the task should run on only one server, similar to laravel onOneServer.

**Comment by PabloKowalczyk** [comment]
Hello,
do you mean https://laravel.com/docs/5.8/scheduling#running-tasks-on-one-server?

**Comment by MarcosGrzeca** [comment]
Exactly, but in the crunz package.

I prefer crunz, because Laravel doesn't have a method to list cron operations.

**Comment by PabloKowalczyk** [comment]
Actually it is implemented in Crunz, but with different name, `preventOverlapping`, https://github.com/lavary/crunz#parallelism-and-the-locking-mechanism. To make sure task runs on only one server you should use one of external lock stores https://symfony.com/doc/current/components/lock.html#available-stores, like PDO, Redis or Memcached.

**Comment by PabloKowalczyk** [comment]
Issue looks like resolved to me, in case of more questions feel free to open new one, I'm closing this one.

**Comment by gennadiylitvinyuk** [comment]
The current implementation of `preventOverlapping` allows passing only locks implementing `BlockingStoreInterface`.

In ths way it is not possible to use `preventOverlapping` to implement something like `onOneServer`, because it leads to double execution - once per server, but not in the same time.

**Comment by PabloKowalczyk** [comment]
Hello @gennadiylitvinyuk, this package is not maintained anymore, please add new issue in https://github.com/crunzphp/crunz.
