### ISSUE TITLE
Force php version

### ISSUE THREAD

**Issue by InformerSoftware** [lavary/crunz#29]
I get a error when the cron is running:
- \* \* \* \* /vendor/bin/crunz schedule:run

PHP Parse error: syntax error, unexpected 'list' (T_LIST) in:
vendor/symfony/config/Definition/ArrayNode.php 

It looks like PHP >= 5.5.0 is required.

I have a Debian server running Plesk. When i create a new cron i can select "Run a command" Or  "Run a PHP script". For a PHP script i can select a PHP version (default is 5.4).

I can't select a version for "Run a command". How can i force crunz to use PHP 5.6. Or can i start the script bij a php script?

**Comment by PabloKowalczyk** [comment]
There is no way to force PHP version inside Crunz. You can force PHP version by running something like this: `* * * * /path/to/bin/php56 /vendor/bin/crunz schedule:run`, the `/path/to/bin/php56` part will use exact PHP bin.
This is issue is not related to Crunz itself, closing.
