### ISSUE TITLE
Specify the config file in the command line

### ISSUE THREAD

**Issue by zhangv** [lavary/crunz#30]
Hi,
Here is the situation, usually we have several different environment(such as production/local development), that means the config is different to each env(such as log file location and some settings). 

Just had a quick looking up in the source code and found out that, I can specify ENV parameter - CRUNZ_BASE_DIR, which will be checked when loading the configuration file(crunz.yml). 

But, CRUNZ_BASE_DIR has to be set in the php code, which is not handy, as I have to write another initializing file which only set CRUNZ_BASE_DIR based on the env and inject it to the crunz running context. For now, the only way is modify the source code, or I have to write a "wrapper" launcher.

So, is it possible to support something like this:
path/to/vendor/bin/crunz schedule:run --conf path/to/crunz.yml

Let me know if I missed something.
Thanks!

**Comment by lavary** [comment]
Having the config file path specified in the command line has been put on the to-do list for this package. It will be included in the next release. 

However, I'd appreciate if you contribute your fixes (if you've done so) to this package.

Thanks again.

**Comment by GlennM** [comment]
By any chance, has this been implemented as mentioned in the comment above?
I don't see it specified in the docs so I'm not sure.
