### ISSUE TITLE
Empty crunz.ERROR: (object(Closure))

### ISSUE THREAD

**Issue by anilcngz** [lavary/crunz#301]
**Crunz version**: 2.1

**PHP version**:  7.2.14

**Description**  
I have a perfectly working Task file in tasks directory. But when i added an array to closure, it starts getting error as below in log file of crunz:

**[2020-04-17 21:41:08] crunz.ERROR: (object(Closure))    [] []**

The test array i added to task as below:

```
$testData = [
              'data' => [
                'type' => 'contact',
                'attributes' => [
                  'email' => 'test'
                ]
              ]
            ];
```

**Comment by PabloKowalczyk** [comment]
Hello, could you paste whole task code?

**Comment by anilcngz** [comment]
Hi Pablo,

Below you can find whole task code which works without error. 
[task.txt](https://github.com/lavary/crunz/files/4496543/task.txt)

When i add the array as below, it starts getting error. 
[taskError.txt](https://github.com/lavary/crunz/files/4496546/taskError.txt)

P.S.: I use different packages in task code, it can be hard to reproduce the error with them. If you prefer i can try to remove other packages and reproduce error. 

Thanks

**Comment by PabloKowalczyk** [comment]
Actually there is a lot of code, what i extracted is:
before:
```php
<?php

use Crunz\Schedule;

$schedule = new Schedule();
$arrayClosureTask = $schedule->run(
    function () {
        $var = 42;
    }
);
$arrayClosureTask
    ->everyMinute()
    ->description('Array closure task')
;

return $schedule;
```

after:
```php
<?php

use Crunz\Schedule;

$schedule = new Schedule();
$arrayClosureTask = $schedule->run(
    function () {
        $var = 42;
        $testData = [
            'testData' => [
                'key' => 'value'
            ]
        ];
    }
);
$arrayClosureTask
    ->everyMinute()
    ->description('Array closure task')
;

return $schedule;
```

And this code works fine, without any errors. Could you prepare minimal reproducer code?
