### ISSUE TITLE
lavary/crunz v2.1.0 requires monolog/monolog ^1.19

### ISSUE THREAD

**Issue by JaminOdabe** [lavary/crunz#303]
**Crunz version**: 2.1.0

**PHP version**: 7.4.5

**Operating system type and version**:
Centos 8

**Description**  
Hi,
trying to install Crunz on a new server, alongside Symfony 5, but looks like a dependency issue prevents that.
Is there a fix?
Crunz is one of the first libraries I use on a new project.
Thanks!

**How to reproduce**  
composer require lavary/crunz

**Additional context**  

![crunz](https://user-images.githubusercontent.com/65193064/81606625-16a19d80-93dc-11ea-949a-6bd61fd50bbf.jpg)

**Comment by PabloKowalczyk** [comment]
Hello, Symfony 5 is compatible with `"monolog/monolog": "^1.25.1|^2"` and Crunz is 100% compatible with Symfony 5. You just need to lower expected monolog version in your `composer.json`, as your screenshot says.

**Comment by JaminOdabe** [comment]
you are right, of course.
thank you for your hard work.
