### ISSUE TITLE
everyOneHundredMinutes() will it work every 100 minutes?

### ISSUE THREAD

**Issue by M-Shahbaz** [lavary/crunz#307]
There's a function in description:

`everyFiveHundredThirtySevenMinutes()`

So will it work on every five hundred thirty seven minutes?

Let's say I want to run task every 100 minutes.
Will run every 100 minutes? e.g: if first time it runs at `00:00` then next would be at `01:40`
`everyOneHundredMinutes()`

Or could be great if possible:
`everyMinutes('100')`

Thanks,

**Comment by PabloKowalczyk** [comment]
Hello, 
short answer: no, long answer: calling `->everyOneHundredMinutes()` will produce expression `*/100 * * * *` with these run dates:
```shell
| Example run dates                                        |
| #1                   | 2020-06-28 08:40:00 Europe/Warsaw |
| #2                   | 2020-06-28 09:40:00 Europe/Warsaw |
| #3                   | 2020-06-28 10:40:00 Europe/Warsaw |
| #4                   | 2020-06-28 11:40:00 Europe/Warsaw |
| #5                   | 2020-06-28 12:40:00 Europe/Warsaw |
```
as you can see it is definitely not every 100 minutes. It is not a bug, this is how Cron works. Probably word `every` is confusing, because it is really `every` only in some cases, like 15 minutes, 20 minutes or 30 minutes, but in other cases it is not `every`, for example calling `everyFortyMinutes` will produce there run dates:
```shell
| Example run dates                                        |
| #1                   | 2020-06-28 08:40:00 Europe/Warsaw |
| #2                   | 2020-06-28 09:00:00 Europe/Warsaw |
| #3                   | 2020-06-28 09:40:00 Europe/Warsaw |
| #4                   | 2020-06-28 10:00:00 Europe/Warsaw |
| #5                   | 2020-06-28 10:40:00 Europe/Warsaw |
```

You can check task's run dates, and other information, by calling Crunz's `task:debug` command.

**Comment by M-Shahbaz** [comment]
How can we have every 100 minutes with crunz
In cron it can be possible with splitting into two tasks e.g: https://stackoverflow.com/a/247643/1865829

**Comment by PabloKowalczyk** [comment]
You can pass Cron expression to task, see https://github.com/lavary/crunz#the-classic-way

**Comment by rogerzanelato** [comment]
@PabloKowalczyk Can you see a way of achieving it with days?

I would like a job to be executed **every X days of the year**.  If I use a cron expression like this `0 0 */3 * *` my job can be executed twice in a row when a new month start.

```shell
| Simulating with Dragonmantank\CronExpression             |
| #1                   | 2020-08-22 00:00:00 Europe/Warsaw |
| #2                   | 2020-08-25 00:00:00 Europe/Warsaw |
| #3                   | 2020-08-28 00:00:00 Europe/Warsaw |
| #4                   | 2020-08-31 00:00:00 Europe/Warsaw |
| #5                   | 2020-09-01 00:00:00 Europe/Warsaw |
```

This example is using three days, but in my real use case it could be any valid day number.

**Comment by PabloKowalczyk** [comment]
Hello @rogerzanelato, what about `0 0 1-30/3 * *`?

**Comment by rogerzanelato** [comment]
> Hello @rogerzanelato, what about `0 0 1-30/3 * *`?

Hello @PabloKowalczyk, sorry for the late answer!

Unfortunately it didn't work, I tested with this expression and it skips the 31th.

```shell
| Simulating with Dragonmantank\CronExpression             |
| #1                   | 2020-08-22 00:00:00 Europe/Warsaw |
| #2                   | 2020-08-25 00:00:00 Europe/Warsaw |
| #3                   | 2020-08-28 00:00:00 Europe/Warsaw | 
| #4                   | 2020-09-01 00:00:00 Europe/Warsaw |
```

But it's okay, I don't think it's something possible with conventional Cron anyway, I think I'll have to handle it in my code. Thank you!

**Comment by PabloKowalczyk** [comment]
No problem, thanks.
