### ISSUE TITLE
Can we Reschedule a task?

### ISSUE THREAD

**Issue by AhtashamImtiyaz** [lavary/crunz#311]
I have a scenario in which i need to reschedule a task.

So we have for example: 
```php
$task = $schedule->run(PHP_BINARY . ' buy.php'); 
$task->on('13:30 2020-08-29');
```

If above work was not accomplished reschedule the task:

`$task->on('18:30 2020-08-29');`

**Comment by PabloKowalczyk** [comment]
Hello,

> If above work was not accomplished reschedule the task:

I think that this is not something that Crunz should be aware of, probably there is some (business) logic behind reschedule decision and why don't you put it in your script (`buy.php`)?

You could also see https://github.com/lavary/crunz#running-conditions.

What do you think?

**Comment by AhtashamImtiyaz** [comment]
I think i cannot use the condition in this scenario, because condition will only run the task if it fullfil while in my case, the task will run for sure and it should run the schedule again if it was not accomplished. For example, buy something on '2020-08-29 at 01:30 pm', we will schedule it with $task->on('13:30 2020-08-29'). But if the item was not available in the stock then it should reschedule buy at certain time again for example: try buying again at $task->on('18:30 2020-08-29');

So, instead of using the binary file, if i use a closure, can i make a change in the current task object and reschedule it or do it need to create another scheduler task in it?

Like this:
```
$task = $schedule->run(function() use ($x) { 
   //can it do something like $task->on('18:30 2020-08-29') here??
});
```

**Comment by PabloKowalczyk** [comment]
How about configuring your job with Cron expression `30 13,18 29 * *` and write appropriate conditions directly in your script?

IMHO Crunz should stay stateless, maybe one day with plugin system there can be option to "remember" last exit code, but this is not something that should be in the core of Crunz.

**Comment by AhtashamImtiyaz** [comment]
umm. Okay i will do it this way. Thanks mate. Nice project. Appreciate your work.

**Comment by PabloKowalczyk** [comment]
Thanks.

**Comment by davidsneighbour** [comment]
A note from the side lines ;) I would implement this by using a task that is run every minute (or every 5 minutes or every hour, depending on your schedules) that is checking in a database for tasks that are scheduled. Those tasks then create a new row with the new run time if required. This procedure should solve your conundrum?

**Comment by AhtashamImtiyaz** [comment]
Thats nice approach
