### ISSUE TITLE
Method 'MonthlyOn' is not supported.

### ISSUE THREAD

**Issue by turtle0x1** [lavary/crunz#317]
**Crunz version**: 2.2.0

**PHP version**: 7.4.8

**Operating system type and version**: ubuntu 20.04

**Description**  

```
xyz@xyz:/dir/$ vendor/bin/crunz schedule:list

In Event.php line 208:
                                        
  Method 'MonthlyOn' is not supported.  

schedule:list [<source>]
```
**How to reproduce**  
```
$task = $schedule->run("task");
$task->MonthlyOn(2, "02:00");
```
**Possible Solution**  
:shrug: 

**Additional context**  
:disappointed:

**Comment by PabloKowalczyk** [comment]
Hello, `monthlyOn` will be a nice addition in the future, currently you can pass Cron expression directly by `cron` method.

**Comment by turtle0x1** [comment]
Okay 😊

Might want to remove it from the READEME https://github.com/lavary/crunz#running-events-at-certain-times

**Comment by PabloKowalczyk** [comment]
> Might want to remove it from the READEME https://github.com/lavary/crunz#running-events-at-certain-times

Good catch, thanks.

**Comment by PabloKowalczyk** [comment]
`MonthlyOn` was removed from documentation in #319, thanks @turtle0x1.
