### ISSUE TITLE
V2.2 log_output out won't disable

### ISSUE THREAD

**Issue by eradin** [lavary/crunz#318]
**Crunz version**: 2.2

**PHP version**: 7.2

**Operating system type and version**: Ubuntu 16.04

**Description**  

With this config, I'm getting a tasks.log file.

log_output: false
output_log_file: /home/wbox/public_html/tasks.log

**How to reproduce**  

**Possible Solution**  

**Additional context**  

Also, as a new feature, it would be nice to have a config setting for max log file size.

**Comment by PabloKowalczyk** [comment]
Fixed in #334, thanks @eradin.
