### ISSUE TITLE
Change config from code

### ISSUE THREAD

**Issue by vionemc** [lavary/crunz#32]
I want to have my default values for some of the fields like email information, but I want my users to be able to modify some of the config.

Can I have only one default config, and then have the other config to modify?

**Comment by lavary** [comment]
Unfortunately, this kind of inheritance is not yet provided with the configuration file, but it will be in the next release, which is coming out next week.
Stay tuned!

**Comment by lavary** [comment]
Closing the issue, feel free to re-open if you have more questions.
