### ISSUE TITLE
Symfony Version >= 2.7 and <  3.0 support

### ISSUE THREAD

**Issue by pjuanda** [lavary/crunz#33]
Currently i have symfony project with symfony version 2.8.x - when trying to install crunz, it rejected because some of the dependecies is for Symfony >= 3.0 like  `symfony/yaml`, `symfony/finder`, and `symfony/process`. Is there any plan for downgrade the lib versions, so it can be use for symfony < 3.0 ?

**Comment by lavary** [comment]
Thanks for reporting this. I'll take a look.
I'll get back to you.

**Comment by devads** [comment]
Any solution for this problem ? I also use symfony 2.8.x and can't install crunz.
Thanks,

**Comment by pjuanda** [comment]
@devads brutal way, you can fork this library, change its minimum-requirements and let's your project point to your forked location. Or, maybe you can try another library like [jobbyphp](https://github.com/jobbyphp/jobby) maybe ?

**Comment by devads** [comment]
I finally upgrade to symfony 3.2, so it's ok now !

**Comment by PabloKowalczyk** [comment]
PR https://github.com/lavary/crunz/pull/74 introduces support for Symfony 2.7/2.8. Closing this issue.
