### ISSUE TITLE
System environment vars not available in php

### ISSUE THREAD

**Issue by pricheal** [lavary/crunz#331]
**Crunz version**: 2.2.2

**PHP version**: 7.4.11

**Operating system type and version**: Running in the `php:7.4-cli` docker image

**Description**  
I am trying to use the php `getenv()` function to get environment variables from the system (docker container) within a closure given to the crunz `run()` function. The environment variables that I know are set on the system (or the docker container) are not appearing. If I use the `getenv()` function on just a standard php script (not connected to crunz or anything, running inside the docker container), the environment variables appear as expected.

**How to reproduce**  
I am experiencing this issue on a bare bones crunz setup and config.

Does anyone have any idea if this is expected behavior or why this might be happening? Thanks for any help.

**Comment by PabloKowalczyk** [comment]
Hello, what about superglobals `$_SERVER` and `$_ENV`, are they also empty?

**Comment by pricheal** [comment]
@PabloKowalczyk Yes, they are also missing the environment variables. I have discovered that if I run the command `vendor/bin/crunz schedule:run` directly in the command line manually myself, the environment variables are available. But not when the `schedule:run` is being activated via the cron. Any idea on why this may be or a potential fix? Here is my `Dockerfile` that sets up the crontab.

```
FROM php:7.4-cli

# update package list
RUN apt-get update

# install cron
RUN apt-get install -y cron

# setup crontab to run crunz scheduler every minute
RUN echo "* * * * * cd /fitdegree/api/jobs/scheduler && /usr/local/bin/php vendor/bin/crunz schedule:run" >> /etc/cron.d/scheduler
RUN crontab /etc/cron.d/scheduler

# install pdo mysql
RUN docker-php-ext-install pdo_mysql

# install unzip (needed by composer)
RUN apt-get install -y unzip

# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# install git (can be needed by some composer installs)
RUN apt-get update
RUN apt-get install -y git

# set working directory to worker directory
WORKDIR /fitdegree/api/jobs/scheduler

# copy composer files
COPY jobs/scheduler/composer.json jobs/scheduler/composer.lock ./

# run composer install
RUN composer install

# set working directory to api
WORKDIR /fitdegree/api

# copy rest of api
COPY . .

# start cron
CMD cron -f
```

**Comment by PabloKowalczyk** [comment]
How did you set up your env vars in container? Cron is run as `root`, what user was used when you run Crunz manually?

**Comment by pricheal** [comment]
The environment variables are being passed in to the container via the `docker run` command. I was also the `root` user when I ran crunz manually.

This seems to be related: https://serverfault.com/questions/337631/crontab-execution-doesnt-have-the-same-environment-variables-as-executing-user

If I manually add the exported env var to the cron command itself, the environment variable appears.
```
# setup crontab to run crunz scheduler every minute
RUN echo "* * * * * export FD_DB_WRITER_HOST=pieball && cd /fitdegree/api/jobs/scheduler && /usr/local/bin/php vendor/bin/crunz schedule:run" >> /etc/cron.d/scheduler
RUN crontab /etc/cron.d/scheduler
```

Seems like the solution here would be to make a bash script or something that explicitly sets up the environment variables needed by the cron process.

**Comment by PabloKowalczyk** [comment]
So, looks like not a problem in Crunz itself?

**Comment by pricheal** [comment]
Yes I believe so, here's a run down of what I've found and how you can get this setup working with docker. 

* Cron process will grab any environment variables set in `/etc/environment`

* Anything ran via the cron tab won't have access to the system environment variables, so something like this won't work:
```
RUN echo "* * * * * env >> /etc/environment && cd /fitdegree/api/jobs/scheduler && /usr/local/bin/php vendor/bin/crunz schedule:run" >> /etc/cron.d/scheduler
RUN crontab /etc/cron.d/scheduler
```
* Anything ran during docker image creation obviously won't have access to environment variables injected into the container at runtime, so this won't work:
```
RUN env >> /etc/environment
```
* So the solution would be to make an `entrypoint.sh` script that gets ran as the `CMD` of the dockerfile, that way the script has access to the injected environment variables, something like this:
```
#!/bin/bash
env >> /etc/environment
cron -f
```

Here are the important parts of the dockerfile:
```
FROM php:7.4-cli
RUN apt-get update
RUN apt-get install -y cron
RUN echo "* * * * * cd /fitdegree/api/jobs/scheduler && /usr/local/bin/php vendor/bin/crunz schedule:run" >> /etc/cron.d/scheduler
RUN crontab /etc/cron.d/scheduler
COPY . .
CMD jobs/scheduler/entrypoint.sh
```

Thanks for the help.

**Comment by PabloKowalczyk** [comment]
Nice description, thanks @pricheal.
