### ISSUE TITLE
Debugging with XDebug

### ISSUE THREAD

**Issue by EduardoSimon** [lavary/crunz#332]
**Description**  
Is possible to debug a task with Xdebug?

**Example**  
I would like to debug tasks in Development using PhpStorm.

**Comment by PabloKowalczyk** [comment]
Hello, actually I never tried that. Under the hood, Crunz spawn new process with task's command, but I really don't know is it possible to debug it.
Maybe Xdebug guys will know how to setup it?

**Comment by rame0** [comment]
I just tried it. It worked without any additional settings
![1](https://user-images.githubusercontent.com/2233607/100458398-c3234280-30d4-11eb-95ba-ea14eeecc0b9.png)

**Comment by EduardoSimon** [comment]
That's great! Could you share your config?

**Comment by rame0** [comment]
My xDebug config is default, except `remote_enable=1`.
And PHPStorm accepting external connections (Settings->Languages & Frameworks->PHP->Debug)

**Comment by EduardoSimon** [comment]
Forgot to say that I have  set it up inside Vagrant, the cron and crunz. Maybe its cuz of that?

**Comment by rame0** [comment]
Can't say about Vagrant. My test environment runs in Docker containers.
