### ISSUE TITLE
Task Life Time - between - 24 hour clock

### ISSUE THREAD

**Issue by anilcngz** [lavary/crunz#357]
**Crunz version**: ^2.2 

**PHP version**: 7.4.16

**Operating system type and version**: Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies

**Description**  
I am trying to add a task which will run every hour between 09:00 and 13:00. But it still works after 13.00. When I checked to documentation, all examples for PM hours and couldn't find a way to run a task as described above. Is there a way to do what I need?

```
$schedule = new Schedule();

$task = $schedule->run(function () {
    Task::queryDeliveryTracking();
});

$task
    ->everyMinute()
    ->between('09:00', '13:00')
    ->preventOverlapping()
    ->description('QueryDeliveryTrackingTasks');
```

**Comment by PabloKowalczyk** [comment]
Hello,

`between` uses closures to limit run dates (which seems to be broken), but you can achieve same result with pure cron expression, try `->cron('0 9-13 * * *')`.
With pure expression you can debug task (`crunz task:debug`) and see example run dates.

**Comment by anilcngz** [comment]
Thank You 👍😊

**Comment by JonLaliberte** [comment]
@PabloKowalczyk Does between still not work correctly?

**Comment by PabloKowalczyk** [comment]
Nothing has changed in `between` method, if You think you found a bug in this method, please create new issue - I will try to fix it.
