### ISSUE TITLE
Tasks order

### ISSUE THREAD

**Issue by davidduda111** [lavary/crunz#358]
**Description**  

Is it possible to define order in which tasks should be executed?

**For example**  

`$task = $schedule->run('echo "Hello there!"')->order(1)->everyMinute();`
`$task = $schedule->run('echo "Hello there again!"')->order(2)->everyMinute();`

**Comment by PabloKowalczyk** [comment]
Hello,
ordering executing is not possible at the moment. What is your use case?

**Comment by rodneyo** [comment]
My particular use case is the following:
I have a task that must run and complete successfully before the second task can run.  Being able to specify the order or better specify that task 1 must complete successfully before running task 2 would be great.   I could possibly accomplish this with an "after()" event call back.  Not sure how I could do this.  task 1 would have to emit some sort of event that task 2 would "listen" for

**Comment by PabloKowalczyk** [comment]
This repo is no longer maintained, please see https://github.com/lavary/crunz/issues/411
