### ISSUE TITLE
some problems whith v2.3.0 but on v1.12.4 and php v5.6 everything is fine

### ISSUE THREAD

**Issue by ishicamiru** [lavary/crunz#359]
**Crunz version**: 2.3.0

**PHP version**: 8.0.0 and  7.4.13

**Operating system type and version*ubuntu v2004*:

**Description**  
devilbox@php-8.0.0 in /shared/httpd/new_sheduler $ vendor/bin/crunz schedule:run

Fatal error: Declaration of Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with Psr\Container\ContainerInterface::has($id) in /shared/httpd/new_sheduler/vendor/symfony/dependency-injection/ServiceLocator.php on line 46

Call Stack:
    0.0001     421984   1. {main}() /shared/httpd/new_sheduler/vendor/lavary/crunz/crunz:0
    0.0037     995328   2. Crunz\Application->__construct($appName = 'Crunz Command Line Interface', $appVersion = 'v2.2.1') /shared/httpd/new_sheduler/vendor/lavary/crunz/crunz:70
    0.0040    1030008   3. Crunz\Application->initializeContainer() /shared/httpd/new_sheduler/vendor/lavary/crunz/src/Application.php:67
    0.0044    1063584   4. Crunz\Application->buildContainer() /shared/httpd/new_sheduler/vendor/lavary/crunz/src/Application.php:119
    0.0044    1063584   5. Composer\Autoload\ClassLoader->loadClass($class = 'Symfony\\Component\\DependencyInjection\\ContainerBuilder') /shared/httpd/new_sheduler/vendor/lavary/crunz/src/Application.php:150
    0.0044    1063712   6. Composer\Autoload\includeFile($file = '/shared/httpd/new_sheduler/vendor/composer/../symfony/dependency-injection/ContainerBuilder.php') /shared/httpd/new_sheduler/vendor/composer/ClassLoader.php:322
    0.0059    1277920   7. include('/shared/httpd/new_sheduler/vendor/symfony/dependency-injection/ContainerBuilder.php') /shared/httpd/new_sheduler/vendor/composer/ClassLoader.php:444
    0.0059    1277920   8. Composer\Autoload\ClassLoader->loadClass($class = 'Symfony\\Component\\DependencyInjection\\Container') /shared/httpd/new_sheduler/vendor/symfony/dependency-injection/ContainerBuilder.php:53
    0.0059    1278048   9. Composer\Autoload\includeFile($file = '/shared/httpd/new_sheduler/vendor/composer/../symfony/dependency-injection/Container.php') /shared/httpd/new_sheduler/vendor/composer/ClassLoader.php:322
    0.0062    1330576  10. include('/shared/httpd/new_sheduler/vendor/symfony/dependency-injection/Container.php') /shared/httpd/new_sheduler/vendor/composer/ClassLoader.php:444
    0.0063    1333912  11. class_exists($class = 'Symfony\\Component\\DependencyInjection\\Argument\\ServiceLocator') /shared/httpd/new_sheduler/vendor/symfony/dependency-injection/Container.php:29
    0.0063    1334040  12. Composer\Autoload\ClassLoader->loadClass($class = 'Symfony\\Component\\DependencyInjection\\Argument\\ServiceLocator') /shared/httpd/new_sheduler/vendor/symfony/dependency-injection/Container.php:29
    0.0063    1334168  13. Composer\Autoload\includeFile($file = '/shared/httpd/new_sheduler/vendor/composer/../symfony/dependency-injection/Argument/ServiceLocator.php') /shared/httpd/new_sheduler/vendor/composer/ClassLoader.php:322
    0.0063    1339944  14. include('/shared/httpd/new_sheduler/vendor/symfony/dependency-injection/Argument/ServiceLocator.php') /shared/httpd/new_sheduler/vendor/composer/ClassLoader.php:444
    0.0063    1339944  15. Composer\Autoload\ClassLoader->loadClass($class = 'Symfony\\Component\\DependencyInjection\\ServiceLocator') /shared/httpd/new_sheduler/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:21
    0.0064    1340072  16. Composer\Autoload\includeFile($file = '/shared/httpd/new_sheduler/vendor/composer/../symfony/dependency-injection/ServiceLocator.php') /shared/httpd/new_sheduler/vendor/composer/ClassLoader.php:322
    0.0066    1362368  17. include('/shared/httpd/new_sheduler/vendor/symfony/dependency-injection/ServiceLocator.php') /shared/httpd/new_sheduler/vendor/composer/ClassLoader.php:444

![image](https://user-images.githubusercontent.com/16159416/115539210-5d16a200-a2a5-11eb-8d35-1c6474f4813f.png)
![image](https://user-images.githubusercontent.com/16159416/115539232-643db000-a2a5-11eb-907a-1dc3ffa86290.png)
![image](https://user-images.githubusercontent.com/16159416/115539332-83d4d880-a2a5-11eb-91b7-6adb83ea889a.png)

**Comment by ishicamiru** [comment]
Possible Workaround  composer require symfony/service-contracts:2.2.0

**Comment by PabloKowalczyk** [comment]
Interesting, please show output of `composer info` and your `composer.json` file.

**Comment by ishicamiru** [comment]
![image](https://user-images.githubusercontent.com/16159416/115691541-d4f8d100-a366-11eb-9488-0ece4e0e116d.png)
![image](https://user-images.githubusercontent.com/16159416/115691587-e04bfc80-a366-11eb-9d2f-fe79f0c45e9e.png)

**Comment by PabloKowalczyk** [comment]
Sorry, I mean `composer info` output without `symfony/service-contracts` dependency.

**Comment by ishicamiru** [comment]
![image](https://user-images.githubusercontent.com/16159416/115718950-4bf09280-a384-11eb-9f26-b35a98d4cfcd.png)
![image](https://user-images.githubusercontent.com/16159416/115719014-5ca10880-a384-11eb-9028-556c9d6a207e.png)

**Comment by PabloKowalczyk** [comment]
I'm trying to reproduce it locally but without success. You could try to remove Crunz cache `/tmp/.crunz` (inside container/VM) and try again. Depedencies' versions seems ok.

**Comment by ishicamiru** [comment]
Sorry, but hasn't helped yet, thanks for your support)

**Comment by PabloKowalczyk** [comment]
Could you create repo with Docker (and `composer.lock` file) to reproduce the issue?

**Comment by ishicamiru** [comment]
https://github.com/ishicamiru/Schedule

**Comment by PabloKowalczyk** [comment]
Tested your repo on Ubuntu with PHP 8.0.3 and Crunz works, so I'm unable to reproduce this issue.

**Comment by ishicamiru** [comment]
https://github.com/ishicamiru/Schedule  sorry, i update repo ,(symfony/service-contracs:2.4.0  as in the original lavary/crunz)

**Comment by PabloKowalczyk** [comment]
Tested code after update but still cannot reproduce issue.

**Comment by ishicamiru** [comment]
problem in using devilbox
https://github.com/jbboehr/php-psr/issues/88

**Comment by ishicamiru** [comment]
for those who use devilbox in the .even file write psr
and re-install lavary / crunz
![image](https://user-images.githubusercontent.com/16159416/116093223-2d093d80-a6af-11eb-9e97-b46608a88254.png)

**Comment by PabloKowalczyk** [comment]
Nice finding. This is why i can't reproduce it on my local machine. Thanks @ishicamiru.
