### ISSUE TITLE
Dynamically set timezone

### ISSUE THREAD

**Issue by turtle0x1** [lavary/crunz#363]
**Description**  
Be able to set timezone either through an environment variable or by passing it as argument.

**Example**  
I run crunz in SNAP container where files cant be edited, but users can be around the world so hard coding a timezone into the file is not an option, would it possible to read this variable from the environment or by passing it in?

Editing `vendor/lavary/crunz/src/Task/Timezone.php` to include the following works for me, buts its probably not very "symfony" (if I knew the symfony way id submit a merge request)

```php
if (isset($_ENV['CRUNZ_TIMEZONE'])) {
    $newTimezone = $_ENV["CRUNZ_TIMEZONE"];
} else {
    $newTimezone = $this->configuration
        ->get('timezone')
    ;
}
```

**Comment by turtle0x1** [comment]
Whoops duplicate

**Comment by PabloKowalczyk** [comment]
Please see https://github.com/lavary/crunz/issues/328 - you can configure timezone per file. Global configuration needs PHP config files which i started to develop but not yet finished.
