### ISSUE TITLE
Execute tasks by using different timezone wise

### ISSUE THREAD

**Issue by adrianbecker013** [lavary/crunz#366]
We have many users and they are using different timezone and so plan is that, send email to these users by their timezone wise. Is it possible to send email by different timezone?

I have tried below but it is not working

```
use Crunz\Schedule;

$schedule = new Schedule();

$task = $schedule->run(PHP_BINARY.' email.php'); 
$task->on('14:35')
     ->timezone('Europe/Warsaw')
     ->description('Send email to users.');

return $schedule;
```

Could you please correct me what is I am doing wrong in it?

**Comment by PabloKowalczyk** [comment]
IMO this is something that should be in your `email.php` script, this is not Crunz responsibility to determine users timezone, but your script (should) have all knowledge about your users. Maybe run task more often and check timezones in script?

**Comment by adrianbecker013** [comment]
@PabloKowalczyk, thanks for your reply on it.

What is use of below timezone()? and when we should use it?. 
```
->timezone('Europe/Warsaw')
````
Could you please give insight on it?

**Comment by PabloKowalczyk** [comment]
Look at example code:
```php
use Crunz\Schedule;

$schedule = new Schedule();

$task = $schedule->run(PHP_BINARY.' email.php'); 
$task->cron('15 14 * * *')
     ->timezone('Europe/Warsaw');

return $schedule;
```
Expression `'15 14 * * *'` means "every day at 14:15" and timezone is used to calculate "14:15".

**Comment by adrianbecker013** [comment]
> Expression `'15 14 * * *'` means "every day at 14:15" and timezone is used to check for"14:15".

I have tested it in locally but it is not working as like above?

**Comment by adrianbecker013** [comment]
We are asking user to fill the timezone, start and end datetime base on these information we need to send email.

**Comment by PabloKowalczyk** [comment]
> CASE : We are asking user to fill the timezone, start and end datetime base on these information we need to send email. So many users may be set same criteria.

This is something that will never land in Crunz core, because it is specific to your domain, as I said earlier: move that logic to your script - this is the best place for it.

> I have tested it in locally but it is not working as like this?

Do you have any reproducer repo? Everything works for me.

**Comment by adrianbecker013** [comment]
> Do you have any reproducer repo? Everything works for me.

We have seted  timezone "America/Los Angeles" in config.yml file so any idea is it occur this?

**Comment by PabloKowalczyk** [comment]
> We have seted timezone "America/Los Angeles" in config.yml file so thats why it is not working?

Actually, what is not working? What was expected behavior/output?

**Comment by adrianbecker013** [comment]
Hello @PabloKowalczyk,

I need your help to execute script as per timezone

```
use Crunz\Schedule;

$schedule = new Schedule();

$task = $schedule->run(PHP_BINARY.' email.php'); 
$task->on('14:35')
     ->timezone('Europe/Warsaw')
     ->description('Send email to users.');

return $schedule;
```

$ vi crunz.yml
timezone: Asia/Calcutta

But script is not working on time of "Europe/Warsaw" timezone, could you please help me what I am doing wrong?

**Comment by PabloKowalczyk** [comment]
> Could you provide list of timezone's are support crunz?

Crunz support all timezones that are supported by PHP - https://www.php.net/manual/en/timezones.php

> And can we do like below?

Yes, that should work.

**Comment by adrianbecker013** [comment]
@PabloKowalczyk, yes I have checked but its not working

**Comment by PabloKowalczyk** [comment]
> Yes, its working fine with date_default_timezone_set('UTC');

Does your issue was solved?

**Comment by adrianbecker013** [comment]
Yes its solved. Thank you @PabloKowalczyk

**Comment by adrianbecker013** [comment]
Resolved my cases so closing this case.
