### ISSUE TITLE
Help to execute many tasks in parallel timing

### ISSUE THREAD

**Issue by adrianbecker013** [lavary/crunz#367]
We need to send email on same time to some of our users.

For example:-
- Send inquiry email on 09:00 o'clock to some of our users and email will be sent on 09:00 o'clock to each users.

Is it possible to send email on same time to some of our users?

**Comment by PabloKowalczyk** [comment]
As I wrote in https://github.com/lavary/crunz/issues/366 - it is up to your application :) Just have all sending logic in your script and do a loop.

**Comment by adrianbecker013** [comment]
PabloKowalczyk, thanks for your reply on it.

Is it possible to execute many tasks in same timing  with crunz ?

**Comment by PabloKowalczyk** [comment]
> Is it possible to execute many tasks in same timing with crunz ?

Yes, it is default behavior to run all task in parallel.

**Comment by adrianbecker013** [comment]
We are developing send email scheduler.

So we will ask user to fill the their timezone, start and end datetime for send email scheduling.  Base on these inforamation will send emails.

So many users may be select and set same timezone, start and end datetime for send email scheduling.

We need to send emails on same datetime with timezone for all those users.

How we can handle this case with crunz?

**Comment by PabloKowalczyk** [comment]
> How we can handle this case with crunz?

Actually Crunz is just "abstraction" around CRON with more features, but it is not designed to send multiple emails based on your choices of your application.

**Comment by adrianbecker013** [comment]
Resolved my cases so closing this case.
