### ISSUE TITLE
hourlyAt not defined

### ISSUE THREAD

**Issue by JonLaliberte** [lavary/crunz#368]
**Crunz version**: 3.0.1

PHP Fatal error:  Uncaught Error: Call to undefined method Crunz\Event::hourlyAt() in ...

Checking the code, it doesn't seem to exist.

Also, calling `hourly()>at('15')` for example doesn't work.

**Comment by PabloKowalczyk** [comment]
Looks like README is wrong and `hourlyAt` method doesn't exist but can be implemented. Would you like to provide PR?

**Comment by boutetnico** [comment]
Any progress on this?
Btw, the readme also mentions `hourlyOn()` which does not exist as well.

**Comment by PabloKowalczyk** [comment]
> Any progress on this?

Done a review, needs some changes.

**Comment by PabloKowalczyk** [comment]
Added in #398
