### ISSUE TITLE
How to run task after completing the previous one?

### ISSUE THREAD

**Issue by Kunstat** [lavary/crunz#369]
**Description**  
Is it possible to run one task only after completing the previous one? Something like synchronous task execution?

**Comment by PabloKowalczyk** [comment]
Currently it is not possible, all tasks run in parallel. What is your use case?

**Comment by Kunstat** [comment]
The application runs a lot of tasks using cron. The problem is that every whole hour is started all at once, which puts an extreme load on the server.

**Comment by PabloKowalczyk** [comment]
IMO it is not a Crunz problem but "running-to-much-every-hour" problem :) You can write "procedural" script that will run all command one-by-one or use async processing (RabbitMQ, Apache Kafka, etc.) if you use one.
