### ISSUE TITLE
onError function

### ISSUE THREAD

**Issue by HMAZonderland** [lavary/crunz#37]
The `onError` function is nice. But it would be nice if we could catch / output exceptions in this function so we can log this somewhere or do anything else with them.

Also the ways we can log is way to restricted at this point. I see you use `Monolog` / `LoggerInterface` implementation. Perhaps we can make it so the developer can set any logger that implemented the `LoggerInterface` interface through the config / constructor of his `Schedule` / `Event` object?

**Comment by lavary** [comment]
Hi,
I'll definitely work on the error and logging features for the next releases.
However, I'd really appreciate if you contribute your fixes (If you've done so) to this package.

Thanks again.
