### ISSUE TITLE
When some php scripts triggered by Crunz, they don't work. Trigger the same scripts in a browser, they work

### ISSUE THREAD

**Issue by jamminjames** [lavary/crunz#370]
I have an issue I can't seem to figure out, having tried many things. When I run certain php scripts via Crunz, they don't work. Trigger the same scripts in a browser, they work fine. 

There are two in particular: one is fetching some apcu variables and emailing the result; the other triggers a session garbage collection (`session_gc()`). Maybe it has to do with the nature of those two operations, but I don't get it. Why would it matter how the script is called, cron job vs the browser? Shouldn't they work either way? Or am I missing something I need to do to get these to work?

I know I have the correct binary php path set, and I know the cron jobs are firing, as they trigger log entries via `sendOutputTo`. Also, in the example of the apcu report email, the email is sent, so I know the file and the cron are working. And as I said, trigger that same script from a browser, and it emails the apcu variable results just fine. Neither uses a function or anything, they both just call the script files.

Any ideas? Love the scheduler. Thanks!

**Comment by PabloKowalczyk** [comment]
Running PHP by "browser" means using `mod_php` or `PHP-FPM`, and running by Crunz uses `CLI`, for some reason you can have different configuration for `mod_php`/`PHP-FPM` and `CLI`, for example different session storage.
If script works by `CLI` directly then check which user runs Crunz, there can be permission issues.

IMO first check is it work directly by `CLI`, probably it is not Crunz issue.

**Comment by jamminjames** [comment]
You are correct, running it via CLI produces the same result.

However, CLI is using the same php version, and `apc.enable_cli` in php.ini is on (`apc.enable_cli=1`). Any idea why it's not working? 

As for the session storage settings for CLI, how do I adjust that? Can't seem to find anything helpful on that.

One thing I noticed is that when I run the `session_gc()` script via the browser, the user is "nginx" (that's when it works), whereas when it runs via CLI, the user is my username (doesn't work). So maybe that's it. Is there a way to run the script as "nginx"?

**Comment by PabloKowalczyk** [comment]
> As for the session storage settings for CLI, how do I adjust that? Can't seem to find anything helpful on that.

Look for PHP config or framework's config if you use one.

But we can agree that this issue is not related to Crunz?

**Comment by jamminjames** [comment]
Yes, not related to Crunz. But I think it's an issue users of Crunz could have to deal with, as I am, so I hope you can stay with me on it and help me solve it, if you can.

One thing I'm trying is to set the uid before the script runs, using your before and after functions and php's `posix_setuid()`, like so:

```
// record for use later, before starting Crunz:
$original_uid = posix_getuid();

// then:
$task = $schedule->run('/usr/bin/php test.php');
$task
   ->hourly()
    ->before(function(){
		posix_setuid(99);
    })
    ->after(function() use ($original_uid){
        posix_setuid($original_uid);
	posix_seteuid($original_uid);
    });
```
Still testing this. What do you think of it as a possible solution?

**Comment by PabloKowalczyk** [comment]
Crunz have `\Crunz\Event::user` method for changing user on Linux OS, using `sudo`, or you can change it on Cron level.

**Comment by jamminjames** [comment]
I don't see anything about that in the documentation. This would permanently change the user for all Crunz operations? How would you do that exactly in CLI?

**Comment by jamminjames** [comment]
I checked out the Event class... so just use `->user("user")` in the task? How would I insert a sudo command into that?

**Comment by PabloKowalczyk** [comment]
> I checked out the Event class... so just use ->user("user") in the task? How would I insert a sudo command into that?

`sudo` will be added automatically.

**Comment by jamminjames** [comment]
I tried adding `->user("user")`, both with the written user name in quotes and with the uid, neither worked -- the php file did not run at all. I added the line like any other in the task, is that how it's supposed to work? Like so?

```
$schedule->run('/usr/bin/php /var/www/session_garbage_collection.php')
        ->everyMinute()
	->sendOutputTo('log/cron_session_gc.log')
        ->user("user");
```

**Comment by PabloKowalczyk** [comment]
Did you check, directly in CLI, that changing user fix your issue?

**Comment by jamminjames** [comment]
Well, I did it with a bash script and it's still not doing the garbage collection, even though it is using the same user as when triggered via browser. So I don't know what else it could be. It's weird, because everyone I talked to seemed to think it was a user issue. 

However, doing it via the task, as shown above, doesn't seem to run the file. It will write to the `cron_session_gc.log`, meaning the task ran, but the `session_garbage_collection.php` file should create another log entry, and it doesn't.

**Comment by PabloKowalczyk** [comment]
OK, looks like this issue is not related to Crunz itself, sorry but i can't help you.

**Comment by jamminjames** [comment]
Well, the `->user("user")` not working is a Crunz issue, seems to me...

**Comment by PabloKowalczyk** [comment]
> Well, the ->user("user") not working is a Crunz issue, seems to me...

Please provide a repository with code to reproduce issue and start a new thread, thanks!
