### ISSUE TITLE
How to test if user() is working?

### ISSUE THREAD

**Issue by jamminjames** [lavary/crunz#373]
I am trying to add the `->user(995)` line to a task. How can I test if it is actually switching to the correct user? I need to switch the user because I am trying to trigger `session_gc()` in a script for garbage collection, but since the Crunz task is performed by the CLI user and `session_gc()` needs to be run for the php user, I need to switch users before triggering the script.

For the task, I have it set up like so (every minute for testing):

```
$schedule->run('/usr/bin/php /var/www/session_garbage_collection.php')
        ->everyMinute()
	->sendOutputTo('log/cron_session_gc.log')
        ->user(995);
```

Is that correct, or does the user line need quotes, like` ->user('995')`?

How can I test via the log if it's actually switching users? As it is, nothing is being written to the log, although it does produce a blank entry. The task is not triggering the garbage collection script, so I am not sure what I'm doing wrong. (The garbage collection script works if I call it via the browser, so I know it's okay.)

Thanks for any help.

**Comment by PabloKowalczyk** [comment]
`user` method under the hood just adds `sudo -u {$passedUser}` to command.
In your example it will be: `sudo -u 995 /usr/bin/php /var/www/session_garbage_collection.php`.
As a general advice: it is better to first test your scripts without Crunz.

**Comment by jamminjames** [comment]
Okay, how does that work without a login before using the 'sudo' command? If I were to use sudo in the CLI, I would have to log in first. And, should `->user(995)` be used without quotes inside the parentheses?

**Comment by PabloKowalczyk** [comment]
> Okay, how does that work without a login before using the 'sudo' command?

Actually it won't work, it assumes there is no need to login. Currently there is no way to ask for password. It is safer to not rely on `user` method and try alternatives like https://github.com/ncopa/su-exec or https://github.com/tianon/gosu - directly in your command.

> And, should ->user(995) be used without quotes inside the parentheses?

If you need to, use `string` version.

**Comment by jamminjames** [comment]
The description for su-exec says it only works for the root user, so I guess this just isn't doable. Thanks anyway.

**Comment by PabloKowalczyk** [comment]
> The description for su-exec says it only works for the root user,

It shouldn't be a problem in Docker container. Of course, everything depends on use case.
