### ISSUE TITLE
Bringing in db via ->run(function() use ($db) fails, but with ->when(function() use ($db), it works

### ISSUE THREAD

**Issue by jamminjames** [lavary/crunz#375]
Crunz version: 2.3.0

PHP version: 7.4

Operating system type and version: Linux, Nginx server

Description:
I'm trying to pass the `$db` variable for use in functions (as in `$db = mysqli_connect($servername, $username, $password, $dbname)`), so that I can access the db within the function.

It works when running a task with 
`->when(function() use ($apcuAvailable,$db)`
but fails when I try to do it with this method:
`$taskvar = $schedule->run(function() use ($apcuAvailable,$db)`
In the latter case, I get the following in the output log:
`PHP Warning:  mysqli_query(): Couldn't fetch mysqli in closure://function() use ($apcuAvailable,$db)`

Why is that, and how can I get it to work? Thanks for your help.

**Comment by PabloKowalczyk** [comment]
Hello, this is expected behavior. `when()` runs in main Crunz process, but each `run()` with Closure  spawns new subprocess, that means nothing is shared between processes and this is why `$db` is not defined.

**Comment by jamminjames** [comment]
Okay, thanks.
