### ISSUE TITLE
How can I unlock that locked by preventOverlapping?

### ISSUE THREAD

**Issue by choi8686** [lavary/crunz#376]
**Crunz version**: 1.4
**PHP version**: 5.6.32

**Operating system type and version**:

**Description**  
Hello, I was using crunz for sending messages, but some files are locking after the server was shut down. 
How can I be unlocked files by preventOverlapping ? 
Thank yo so much.

**Comment by PabloKowalczyk** [comment]
Hello, version `1.4`, and `v1.x` branch, is no longer supported, please update Crunz to at least `v2.3.1`.
