### ISSUE TITLE
Command delay / sleep?

### ISSUE THREAD

**Issue by pips-** [lavary/crunz#388]
Hello,

Many thanks for this great project!

I'm working on a legacy application using some (a lot?) of cron jobs to do background tasks. 
Also, as SAAS provider, my company hosts several instances of this application for each of our clients on the same server, but in different vhost folders.

In order to reduce the work load for theses tasks, we use `sleep $((RANDOM \% 3600)) && php /path/to/project/task` in order to avoid strictly same-time task runs but ensure the job will run once during the hour.

As I try to convert our crontab, I attempted to do this:

```php
<?php

use Crunz\Schedule;

$scheduler = new Schedule();

$delay = random_int(0, 3600);
$scheduler->run('sleep '.$delay.' ; '.PHP_BINARY.' /path/to/projects/task')
    ->preventOverlapping()
    ->everyTwoMinutes()
;

return $scheduler;
```

But this will also completely defeat the `preventOverlapping()` mechanism.

Is there any way to add a delay / sleep to task run?

**Comment by PabloKowalczyk** [comment]
Hello, what about calling `sleep` inside PHP, in your script `/path/to/projects/task`?

**Comment by pips-** [comment]
Yes, I thought about that,  the twist is in some cases we will want to run the script from the command line and the sleep/delay would not be desirable.

So I'm considering adding a simple parameter to our scripts to add that kind of sleep/delay in Crunz specific calls.

However, as there is no proper way to do this currently, do you think adding a delay function could be interesting for Crunz? I can try to come back with a PR for this :)

**Comment by PabloKowalczyk** [comment]
Actually this is the first time someone asking for this feature so I don't think it is needed in core now, thank you.

**Comment by RancherUserMaker** [comment]
bump

**Comment by PabloKowalczyk** [comment]
@RancherUserMaker this repo is no longer maintained, please create new issue in [crunzphp/crunz](https://github.com/crunzphp/crunz)
