### ISSUE TITLE
Why is illuminate/support a dependency?

### ISSUE THREAD

**Issue by boosis** [lavary/crunz#4]
I haven't used this yet, but could you tell me why illuminate/support is a dependency? I didn't see where you used this library.

**Comment by rossbearman** [comment]
The only usage I can find in the code is the `Mailer` contract `Illuminate\Contracts\Mail\Mailer` in `Event.php`. 

`illuminate/support` shouldn't be a dependency of a framework-agnostic package as it is a huge package itself, with a number of dependencies.  It's intended to provide support packages for the Laravel framework itself and not really intended for use elsewhere, unless you're building a Laravel specific package that can be tied to a specific Laravel version.

**Comment by boosis** [comment]
Yes, I saw that. Even there it's only namespace, Mailer class is not used anywhere in that class

**Comment by lavary** [comment]
@rossbearman illuminate/support was used for a couple of helper functions like `array_get()`, `array_only`, `collect`, and a few others. However, this dependency has been removed in the latest release of Crunz, which is 1.1.1.

The reference to Illuminate\Contracts\Mail\Mailer has been removed as well.

**Comment by rossbearman** [comment]
Good job, thanks for resolving this.
