### ISSUE TITLE
Custom files finder / initialization strategy

### ISSUE THREAD

**Issue by spotman** [lavary/crunz#40]
Hi there!

Thanks for this awesome library!

I want to use Crunz in CMF with multiple directories for scheduled events files (app, core and some modules). These directories are detected dynamically and can not be set via cli argument or yml config.  As I understood doc and the code correctly, it's not possible to configure Crunz to use custom files finder. So my suggestion is to implement special class which would handle files detecting/loading and use it instead of [collectTaskFiles](https://github.com/lavary/crunz/blob/master/src/Console/Command/ScheduleListCommand.php#L87) method (and it's clones in other files). But I don't see any way to inject this file into crunz console app (maybe create namespace for these loaders, set loader codename in config and search loader class in namespace by specified codename). I may make PR for this but I want to hear your opinion for this issue first.

**Comment by lavary** [comment]
Hi, thanks for the comment. I think that's a fantastic idea. I'd appreciate if we can cooperate on this.

**Comment by iluuu1994** [comment]
We're really interested in this. I will spend a few hours to make this happen. Do you have a preferred way you want this to be implemented? For our use case we need to specify two static task directories but maybe it would make sense to allow specifying some service that collects the tasks as suggested here.

**Comment by spotman** [comment]
@iluuu1994 are you asking me or the library maintainer?

**Comment by iluuu1994** [comment]
The maintainer 🙂

**Comment by PabloKowalczyk** [comment]
Hello guys,

> we need to specify two static task directories

Currently Crunz's task loader search for files recursively, so setting `/var/www/html` as a source, and placing tasks in `/var/www/html/A` and `/var/www/html/B` should do the trick. BTW you can use symlinks.

**Comment by iluuu1994** [comment]
Thanks for your tip, that might work. Are you still interested in a more general solution? A single directory is pretty limiting. We'll have to make our framework automatically symlink the two directories which surely works but isn't super elegant.

**Comment by PabloKowalczyk** [comment]
Generic solution would be awesome, but developing it will take time. Ideally Crunz should provide some plugin api to ease customizing some aspects Crunz itself.
