### ISSUE TITLE
Allow the crunz.yml file to be in a subfolder

### ISSUE THREAD

**Issue by scollovati** [lavary/crunz#404]
**Description**  
Please allow the `crunz.yml` file to be in a subfolder.  I usually don't put the app configs in the root of the project, but into a dedicated folder (usually not checked in in git).

**Example**  
Maybe adding a `--config` flag to the CLI may be sufficient for this use case. The result would be
```
vendor/bin/crunz --config config/crunz.yml schedule:run
```

**Comment by PabloKowalczyk** [comment]
Would you like to provide a PR?
