### ISSUE TITLE
Readme. Out of date the "Contributing" section

### ISSUE THREAD

**Issue by vommuan** [lavary/crunz#408]
Now it looks like...

"Which branch should I choose?
In most cases you should target branch 1.12.x, as this is active development branch. Branch master is for future release, but all bugs/features should go to 1.11.x anyway."

Current version of package is v3.2.1. So there is a misunderstanding, in what branch I can contribute.

It will be good to update contributing section.

**Comment by PabloKowalczyk** [comment]
Fixed in https://github.com/crunzphp/crunz/pull/6 and please migrate #411
Thanks @vommuan!
