### ISSUE TITLE
Job only fire once and not run again

### ISSUE THREAD

**Issue by mdjaman** [lavary/crunz#413]
**Crunz version**: 2.3.1

**PHP version**: 7.4

**Operating system type and version**: MacOS Ventura

**Description**  
Job only fired once and not run again

**How to reproduce**  
in my crontab : `* * * * * cd ~/Projects/stelab && php vendor/bin/crunz schedule:run`

`use Crunz\Schedule;

require __DIR__ . '/../vendor/autoload.php';

$schedule = new Schedule();

$cmd = sprintf(
    'cd %s && touch $RANDOM',
    __DIR__ . '/../data/log'
);
$task = $schedule->run($cmd);
$task
    ->description('Simple Task')
    ->everyMinute()
    ->preventOverlapping();

return $schedule;
`

**Comment by PabloKowalczyk** [comment]
Hello, this repo is no longer maintained, please use https://github.com/crunzphp/crunz

**Comment by mdjaman** [comment]
Upgraded to 3.4 and still same result
