### ISSUE TITLE
Job stats and management

### ISSUE THREAD

**Issue by cidious** [lavary/crunz#47]
Hello,
just a feature request:
do you mind to add the following stats functions:
1. what job will be run next
2. what jobs have been running now
3. what job has finished last
4. detect the job error level (bool error/success or unix int 0=success or >0=error code)
5. job naming to ease the management

**Comment by cidious** [comment]
Hello, no thanks, but it would be nice to have.

**Comment by PabloKowalczyk** [comment]
Closing due to lack of responses from author.
