### ISSUE TITLE
Neither appendOutputTo() or sendOutputTo() works

### ISSUE THREAD

**Issue by weiminzhen** [lavary/crunz#48]
**Here is my code:**

```bash
use Crunz\Schedule;
$schedule = new Schedule();
$schedule->run('date')
    ->everyMinute()
    ->sendOutputTo('/tmp/test')
    ->description('test');
return $schedule;
```

**and my /etc/crontab:**

```bash
* * * * * root /var/www/shield/vender/bin/crunz schedule:run
```

All my Schedules work fine.
But,When I try to user sendOutputTo(),I get no output in /tmp/test.
It works if I redirect output to file in /etc/crontab:

```bash
* * * * * root /var/www/shield/vender/bin/crunz schedule:run >> /tmp/test
```

**So.**
How can I send output of each job to individual file.

**Thank you.**

**Comment by clindh** [comment]
I can't get this to work either
