### ISSUE TITLE
Using another root directory for everything

### ISSUE THREAD

**Issue by clindh** [lavary/crunz#49]
What is the best way to use another root directory for crunz? I rather not have my task nor configuration file in the composer/ directory.

I know it is possible for the `schedule:run` and `schedule:list` 
_We can explicitly set the source path by passing it to the event runner as a parameter_

But this applies only to finding the tasks?  It still seems to require config file in composer/.  
An optional --rootdirectory option to "crunz" would be great.

**Comment by PabloKowalczyk** [comment]
Hi, maybe option to specify config file will help? For example: `crunz --config-file /path/to/config/file.yml`?

**Comment by PabloKowalczyk** [comment]
No response from author - closing. Feel free to open new issue, thanks.
