### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by smehtaCAS** [lavary/crunz#52]
Hi,

I am trying to install the using composer - composer.phar require  lavary/crunz

I am getting the following error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: lavary/crunz[v1.4.8, dev-master].
    - Can only install one of: lavary/crunz[v1.4.8, dev-master].
    - Installation request for lavary/crunz ^1.4.8 -> satisfiable by lavary/crunz[v1.4.8].
    - Installation request for lavary/crunz dev-master -> satisfiable by lavary/crunz[dev-master].

Any idea what can be the fix?

Thanks!

**Comment by smehtaCAS** [comment]
Any suggestion? Thanks.

**Comment by PabloKowalczyk** [comment]
Hello @smehtaCAS, do you still face this issue?

**Comment by smehtaCAS** [comment]
It was a dependency issue. I do not remember how I got it to work. Haven't tried recently though. Thanks.

**Comment by PabloKowalczyk** [comment]
Ok, i will close this issue. Please open new one if you face this issue again. Thanks.
