### ISSUE TITLE
Event:sudo is not correct

### ISSUE THREAD

**Issue by cjunge-work** [lavary/crunz#55]
On line https://github.com/lavary/crunz/blob/master/src/Event.php#L200 there is a call to `$this->sudo()`, but the definition at https://github.com/lavary/crunz/blob/master/src/Event.php#L222-L225 is  `protected function sudo($user)` with the `$user` parameter being used.

Also, on https://github.com/lavary/crunz/blob/master/src/Event.php#L207 the call to sudo() is not appended to the `$command`, so nothing will happen with the returned value.

I believe that `sudo()` should use `$this->user` as the value and that https://github.com/lavary/crunz/blob/master/src/Event.php#L207 should append it to `$command`

**Comment by PabloKowalczyk** [comment]
You are right. Fixed in https://github.com/lavary/crunz/pull/85, thank you.
