### ISSUE TITLE
Getting namespace error

### ISSUE THREAD

**Issue by manojsb** [lavary/crunz#57]
Hi

In my PHPStorm it's giving error for namespace
![screenshot from 2017-05-15 11-15-11](https://cloud.githubusercontent.com/assets/25655962/26044286/0219cf50-3961-11e7-9f1f-a4525673ca7e.png)

**Comment by PabloKowalczyk** [comment]
Hello @manojsb, do you still face this issue?

**Comment by PabloKowalczyk** [comment]
Actually this was fixed in https://github.com/lavary/crunz/commit/3d3bf65bd1cabacba1ed9831ddc7d5b686ae50b2
