### ISSUE TITLE
delete,pause task from scheduler list by id

### ISSUE THREAD

**Issue by allen-ecu** [lavary/crunz#58]
Hi guys,

do we have the ability to delte or pause a specific task by id throught command?

e.g.
crunz tasks remove 1
crunz tasks pause 2
crunz tasks resume 1

at the moment, we can't delete the task from the list, can we?

**Comment by PabloKowalczyk** [comment]
Hello, currently this is no way do this. Do you mean `crunz tasks:remove 1` remove entire file?
What `pause` should do?

**Comment by PabloKowalczyk** [comment]
I close because of the lack of response from the author.
