### ISSUE TITLE
Supported for PHP 5.3

### ISSUE THREAD

**Issue by nvkhoa666** [lavary/crunz#59]
Hi,

I really like your library, it is super useful. I just wonder what is the reason for this library to require PHP 5.5? We have quite old server software and we can't upgrade to newer PHP version at the moment (only has PHP5.3). Thank you.

**Comment by PabloKowalczyk** [comment]
Hello,

PHP 5.3 is very old and is not supported from about 4 years. There should be really good reason to support that old version.
You can install Crunz next to your app and run Crunz with PHP 5.6 while your app will be using PHP 5.3. Please note that Crunz is app independent.
I hope it will clear some things.
