### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by boosis** [lavary/crunz#6]
When I run this on my ubuntu box I get the following error

`PHP Fatal error:  Class 'Crunz\console\Commands\ScheduleRunCommand' not found in /var/www/xxxx/vendor/lavary/crunz/src/Console/CommandKernel.php on line 31
PHP Stack trace:
PHP   1. {main}() /var/www/xxxx/vendor/lavary/crunz/crunz:0
PHP   2. Crunz\Console\CommandKernel->__construct() /var/www/xxxx/vendor/lavary/crunz/crunz:37`

Can it be because of small 'c' on 'console'

**Comment by lavary** [comment]
Would you please update the library to version v1.1.2 (latest version).
This should be the cause of the issue in your environment. please let me if the issue is resolved.

Thanks.

**Comment by boosis** [comment]
That fixed it. Thanks.
