### ISSUE TITLE
Schedule closure function outputs empty crunz.ERROR

### ISSUE THREAD

**Issue by svjacob** [lavary/crunz#65]
```
use Crunz\Schedule;

$schedule = new Schedule();
$schedule->run(function()  {
         });

return $schedule;
```

When I run a schedule command that's a closure function, I get 

`crunz.ERROR:  [] []`

outputted to my error log. 

Not a big issue, but annoying to fill up my crunz error log with this? Any idea what's happening?

**Comment by PabloKowalczyk** [comment]
Fixed in https://github.com/lavary/crunz/pull/87, thanks for the report.
