### ISSUE TITLE
SMTP setup does not work correctly

### ISSUE THREAD

**Issue by lasanthaa** [lavary/crunz#66]
Hi
I ran the code using ssh in my server.
/usr/local/bin/php /home/souvenir/public_html/new/cron2/vendor/lavary/crunz/crunz schedule:run

But i got error saying "Invalid type for path "crunz.smtp". Expected array, but got strings"
My smtp set up is 

```
smtp:
    host:mail.domain.com 
    port:465
    username:*****
    password:admin1234
    encryption:SSL/TLS 
```

Is there anyone who faced this issue?
Thank you

**Comment by PabloKowalczyk** [comment]
Possibly outdated issue. Feel free to open new if you still face this problem.
