### ISSUE TITLE
No task is due

### ISSUE THREAD

**Issue by boosis** [lavary/crunz#7]
I have the following task
`
$schedule->run('/var/www/xxxx/bin/console.php cron:import-listings')
->cron('59 * * * *')
    ->appendOutputTo('/var/log/xxxx.log')
    ->preventOverlapping();
`
I keep changing the minute to see if it works but I only see No task is due when  time matches the cron value. Am I missing something?

**Comment by lavary** [comment]
Is your system timezone different than the time zone configured in your `php.ini` file?
Also please run `crunz schedule:list` command to see if the task is scheduled as expected.

**Comment by lavary** [comment]
You can set a certain time zone for each event individually:

```php
<?php
// ...
$schedule->run('/var/www/xxxx/bin/console.php cron:import-listings')
                 ->cron('59 * * * *')
                ->timezone('Europe/London')
                 ->appendOutputTo('/var/log/xxxx.log')
                 ->preventOverlapping();

```

**Comment by boosis** [comment]
Why does the timezone matter? Isn't it 59 minutes past every hour, so it shouldn't matter which timezone the server or php is, or am I missing something?

**Comment by lavary** [comment]
Normally you don't have to set a time zone for a task unless you can't modify the timezone in the `php.ini` file (Crunz uses Carbon for date-related operations) or if you want to schedule events based on different time zones. You're looking at your local time waiting for the event to take place while the current time in your PHP server might be different.

**Comment by lavary** [comment]
@boosis Did this work for you?

**Comment by lavary** [comment]
Closing the issue. Please feel free to reopen if you encounter any similar issues.
