### ISSUE TITLE
Always getting "No event is due! "

### ISSUE THREAD

**Issue by madhukumaar** [lavary/crunz#70]
After running `vendor/bin/crunz schedule:list`

I have the following, but the cron log is always saying: No event is due! 

+-----+---------------------------------------+-----------------+----------------------------------------------------------------------+
| #   | Task                                  | Expression      | Command to Run                                                       |
+-----+---------------------------------------+-----------------+----------------------------------------------------------------------+
| 1   | XXXXXX      | 30 9 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 8190              |
| 2   | XXXXXX      | 30 9 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 8678              |
| 3   | XXXXXX      | * 23 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 237               |
| 4   | XXXXXX      | 30 9 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 3758              |
| 5   | XXXXXX      | 30 9 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 7024              |
| 6   | XXXXXX      | 30 9 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 8186              |
| 7   | XXXXXX      | 30 9 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 8686              |
| 8   | XXXXXX      | 30 9 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 9146              |
| 9   | XXXXXX      | * 2 16 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run1 9305              |
| 10  | XXXXXX      | 30 9 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 8191              |
| 11  | XXXXXX      | * 5 16 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run1 3272              |
| 12  | XXXXXX      | * 23 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 3901              |
| 13  | XXXXXX      | * 23 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 243               |
| 14  | XXXXXX      | * 21 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 6966              |
| 15  | XXXXXX      | * 23 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 5278              |
| 16  | XXXXXX      | * 12 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 9059              |
| 17  | XXXXXX      | * 4 16 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run1 3259              |
| 18  | XXXXXX      | * 20 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 5106              |
| 19  | XXXXXX      | 30 9 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 8179              |
| 20  | XXXXXX      | 30 9 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 8687              |
| 21  | XXXXXX      | * 14 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run1 3371              |
| 22  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 12.90_77.60   |
| 23  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 18.95_72.80   |
| 24  | YYYYYYY       | 30 22 15 11 * * | /usr/bin/php /home/sample/jobs/runner.php run2 35.10_-117.90 |
| 25  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 13.05_77.60   |
| 26  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 28.65_77.20   |
| 27  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 25.20_75.85   |
| 28  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 13.10_77.55   |
| 29  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 20.00_77.00   |
| 30  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 10.00_76.40   |
| 31  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 12.95_77.55   |
| 32  | YYYYYYY       | 30 1 16 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run2 -36.90_174.80 |
| 33  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 12.90_77.55   |
| 34  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 10.00_76.30   |
| 35  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 13.00_77.55   |
| 36  | YYYYYYY       | 30 4 16 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run2 -27.40_153.05 |
| 37  | YYYYYYY       | 30 22 15 11 * * | /usr/bin/php /home/sample/jobs/runner.php run2 37.35_-122.10 |
| 38  | YYYYYYY       | 30 22 15 11 * * | /usr/bin/php /home/sample/jobs/runner.php run2 37.40_-122.10 |
| 39  | YYYYYYY       | 30 22 15 11 * * | /usr/bin/php /home/sample/jobs/runner.php run2 34.10_-118.30 |
| 40  | YYYYYYY       | 30 20 15 11 * * | /usr/bin/php /home/sample/jobs/runner.php run2 17.20_-88.90  |
| 41  | YYYYYYY       | 30 20 15 11 * * | /usr/bin/php /home/sample/jobs/runner.php run2 17.25_-88.70  |
| 42  | YYYYYYY       | 30 22 15 11 * * | /usr/bin/php /home/sample/jobs/runner.php run2 36.20_-115.10 |
| 43  | YYYYYYY       | 30 11 15 11 * * | /usr/bin/php /home/sample/jobs/runner.php run2 0.40_33.20    |
| 44  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 10.00_76.35   |
| 45  | YYYYYYY       | 30 3 16 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run2 -33.90_150.75 |
| 46  | YYYYYYY       | 30 19 15 11 * * | /usr/bin/php /home/sample/jobs/runner.php run2 40.70_-74.00  |
| 47  | YYYYYYY       | 30 1 16 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run2 -36.70_174.80 |
| 48  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 28.70_77.20   |
| 49  | YYYYYYY       | * 9 15 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run2 12.30_76.55   |
| 50  | YYYYYYY       | 30 13 15 11 * * | /usr/bin/php /home/sample/jobs/runner.php run2 47.50_19.00   |
| 51  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 12.90_77.60        |
| 52  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 18.95_72.80        |
| 53  | ZZZZZZ            | * 22 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 35.10_-117.90      |
| 54  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 13.05_77.60        |
| 55  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 28.65_77.20        |
| 56  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 25.20_75.85        |
| 57  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 13.10_77.55        |
| 58  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 20.00_77.00        |
| 59  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 10.00_76.40        |
| 60  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 12.95_77.55        |
| 61  | ZZZZZZ            | * 1 16 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run3 -36.90_174.80      |
| 62  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 12.90_77.55        |
| 63  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 10.00_76.30        |
| 64  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 13.00_77.55        |
| 65  | ZZZZZZ            | * 4 16 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run3 -27.40_153.05      |
| 66  | ZZZZZZ            | * 22 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 37.35_-122.10      |
| 67  | ZZZZZZ            | * 22 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 37.40_-122.10      |
| 68  | ZZZZZZ            | * 22 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 34.10_-118.30      |
| 69  | ZZZZZZ            | * 20 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 17.20_-88.90       |
| 70  | ZZZZZZ            | * 20 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 17.25_-88.70       |
| 71  | ZZZZZZ            | * 22 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 36.20_-115.10      |
| 72  | ZZZZZZ            | * 11 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 0.40_33.20         |
| 73  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 10.00_76.35        |
| 74  | ZZZZZZ            | * 3 16 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run3 -33.90_150.75      |
| 75  | ZZZZZZ            | * 19 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 40.70_-74.00       |
| 76  | ZZZZZZ            | * 1 16 11 * *   | /usr/bin/php /home/sample/jobs/runner.php run3 -36.70_174.80      |
| 77  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 28.70_77.20        |
| 78  | ZZZZZZ            | 30 8 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 12.30_76.55        |
| 79  | ZZZZZZ            | * 13 15 11 * *  | /usr/bin/php /home/sample/jobs/runner.php run3 47.50_19.00        |
+-----+---------------------------------------+-----------------+----------------------------------------------------------------------+

I used a test task to run every minute, every 2 minutes and so on, they seem to be working but all these crons are not working, getting same value as "No event is due! "

**Comment by josenano** [comment]
Seems like this project has been abandoned by the dev. But I am still using it and is working fine for me. I have tried every minute, daily, and weekly so far.

**Comment by anmoroz** [comment]
It looks like that.

**Comment by dhastings** [comment]
Ensure that your timezone is set. I had set my system timezone, but I forgot to set date.timezone in my php.ini. Alternately, you can set a timezone for each task using the timezone() method. Hope this helps.

**Comment by PabloKowalczyk** [comment]
@madhukumaar could you show how you configured tasks run date?

**Comment by PabloKowalczyk** [comment]
PR #94 added `timezone` key to config. This option is now required so this will lower confusion about tasks' run time.
