### ISSUE TITLE
New package maintainer

### ISSUE THREAD

**Issue by digilist** [lavary/crunz#71]
Hello. It looks like this package got abandoned and there is nobody looking into issues and pull requests.

@lavary would mind giving another person write access to this repository if somebody is willing to take responsibility for this repository?

**Comment by lavary** [comment]
Hi Markus,
Thanks for bringing this up. I've been actually looking for someone to help me maintain this package.
Anyone who's interested to be a collaborator, just drop me an email. 

Thanks!

**Comment by PabloKowalczyk** [comment]
@lavary Check your e-mail :)

**Comment by royord** [comment]
Is this transition under way, I notice that there are a number of forks that are ahead of the master.

**Comment by PabloKowalczyk** [comment]
@royord i just received push permission and i will do some merges, cleanups and releases.
