### ISSUE TITLE
Monolog 2.0 support

### ISSUE THREAD

**Issue by marcusirgens** [lavary/crunz#78]
Hi!

I'm wondering if you're planning to add monolog 2.0 support? I tried cloning and running crunz locally with monolog 2.0, and it seems to work fine, so I'm assuming a version bump in the composer file should suffice.

Marcus

**Comment by PabloKowalczyk** [comment]
Hello,

i think it is not a problem to support Monolog 2, but there is no official release of 2 version. Milestone for v2 is on 75% - https://github.com/Seldaek/monolog/milestone/1 and the question is why you use Monolog 2 in your project? `dev-master` is not meant for production use.
Could you tell me your use case?

**Comment by PabloKowalczyk** [comment]
There is no further answers from author, also date of release of `Monolog` v2 is not known so i will close this issue. Feel free to open new issue when `Monolog` will be v2 :)
