### ISSUE TITLE
Task runs every minute of hour with on()  

### ISSUE THREAD

**Issue by HilbertGilbertson** [lavary/crunz#83]
The `on` method supposedly supports any string that can be parsed with strtotime, except it has a problem with the minute on the hour. Here's my problem example:

`->on("Thursday 11:01")` runs once today (Thursday) at 11:01 UTC. But if changed to `->on("Thursday 11:00")` the same task runs on each call of `schedule:run` until 11:59 (11:00, 11:01, 11:02, 11:03, etc; with the standard crunz setup, this means this task runs 60 times instead of once).

While I can see that this might make some sense insofar as crunz executes the task for every minute of the hour, this does not follow the format of strtotime, as the string `Thursday 11:00` would equal the next/current Thursday at the first second of the eleventh hour (today being 1524135600).

**Comment by PabloKowalczyk** [comment]
Hi, expected behavior of `->on('8:00')` is to run task only at 8:00, not on 8:00, 8:01 etc. Fixing it was easy - just make strict comparisons. Thanks @HilbertGilbertson.
