### ISSUE TITLE
Problems with Freebsd

### ISSUE THREAD

**Issue by anmoroz** [lavary/crunz#9]
Hi.
On a server running FreeBSD I got an error "Ambiguous output redirect."
Because structure "**2>&1**" is not working with shell **csh**
I propose to to make check OS in Event class, method buildCommand and fix command.

```
$command  = $this->command . $redirect . $this->output;
$command .= (stristr(strtolower(PHP_OS), 'bsd')) ? ' &' : ' 2>&1 &';
```

**Comment by PabloKowalczyk** [comment]
https://github.com/lavary/crunz/pull/13

**Comment by PabloKowalczyk** [comment]
No response to issue or PR - closing. Feel free to open new issue/PR if you still experience this problem.
