### ISSUE TITLE
Class 'Crunz\Schedule' not found 

### ISSUE THREAD

**Issue by RaeesAbbas** [lavary/crunz#91]
**it is the ERROR:** 
Fatal error: Uncaught Error: Class 'Crunz\Schedule' not found Stack trace: #0 {main} throw ..
 **Here is the code:**
use Crunz\Schedule;
$schedule = new Schedule();
$schedule->run('test2.php');       
         $schedule->everyMinute();
         $schedule->description('mail testing');
         
return $schedule;

**Comment by PabloKowalczyk** [comment]
Hello.
Code that you provide doesn't work but from other reason than `Fatal error: Uncaught Error: Class 'Crunz\Schedule' not found`, actual error is `Fatal error: Call to undefined method Crunz\Schedule::everyMinute()`.
Here is the working code:
```
<?php

use Crunz\Schedule;

$schedule = new Schedule();

// Note that run method returns Event instance
$event = $schedule->run('test2.php');
$event->everyMinute();
$event->description('mail testing');

return $schedule;
```
Does it help?

**Comment by RaeesAbbas** [comment]
Error is same
**Fatal error:  Class 'Crunz\Schedule' not found  Stack trace: #0 {main} thrown in :** 
**Here is my code's look now:**  
`<?php
use Crunz\Schedule;
$schedule = new Schedule();
// Note that run method returns Event instance
$event = $schedule->run('test2.php');
$event->everyMinute();
$event->description('mail testing');
return $schedule;
?>
`

**Comment by PabloKowalczyk** [comment]
Could you tell me which Crunz version you use, what is your OS and do you run `crunz schedulre:run` command?

**Comment by RaeesAbbas** [comment]
i am using windows 10 and 1.6 version of Crunz.

**Comment by PabloKowalczyk** [comment]
Do you run Crunz by `php vendor\bin\crunz schedule:run` command?

**Comment by PabloKowalczyk** [comment]
Crunz is not meant to be run by browser. proper usage for Crunz is to configure Cron to run `php crunz schedule: run` every minute.
To avoid error you need to require `autoload.php` generated by `Composer` - `require_once 'vendor\autoload.php'`, but if you run task file directly by browser, configured command won't be run because this is Crunz responsibility to run task on specific, configured, time.

**Comment by RaeesAbbas** [comment]
By` crunz schedule:run`  command i got  no event is due ...
![image](https://user-images.githubusercontent.com/18502684/40277657-16001264-5c3c-11e8-9336-14a156ead8a2.png)

**Comment by PabloKowalczyk** [comment]
Try to call `vendor\bin\crunz schedulre:run` from `LocalMailTester` directory.

**Comment by RaeesAbbas** [comment]
do you mean `schdule:run` instead of `schedulre:run` .
![image](https://user-images.githubusercontent.com/18502684/40277747-ddc76530-5c3d-11e8-9a3d-6a417f9b616c.png)
 now i change it to `schdule:run ` and got folllowing , is it mean its ok no problem  .
![image](https://user-images.githubusercontent.com/18502684/40277791-670d5494-5c3e-11e8-8ad6-3ac3f0f72a47.png)

**Comment by PabloKowalczyk** [comment]
Of course `schedule:run`, i've edited comment. Did you properly configure Crunz with task suffix and task directory?
Could you show result of command `vendor\bin\crunz schedule:list`?

**Comment by RaeesAbbas** [comment]
now i need to configure Crunz with tasks suffix and task directory right?
![image](https://user-images.githubusercontent.com/18502684/40277864-f0b1aea6-5c3f-11e8-9f85-5ffce8460a93.png)

kindly guide me to configure on windows.
i created directory `tasks` in projects root directory and a file named as `Tasks.php` and also place  file `test2.php` near with `Tasks.php` .    I configure `Tasks.php`  to run task file as  ` $event = $schedule->run('test2.php'); ` 
Am i am on right way?

**Comment by RaeesAbbas** [comment]
Is  i need to  use `make:task` to configure explicitly tasks directory and suffix?
As i described above in   `Tasks.php`  i configure  `$event = $schedule->run('test2.php');  `  file.  `test2.php` is  in same directory as   `Tasks.php ` .  Is  i need to `php  vendor\bin\crunz schedulre:run`  to configure Cron to run every minute , in my case i am on windows have  Task scheduler App not cron  ?

**Comment by PabloKowalczyk** [comment]
> Is i need to use make:task to configure explicitly tasks directory and suffix?

You can create config file by `vendor\bin\crunz publish:config`.

>  Is i need to php vendor\bin\crunz schedulre:run to configure Cron to run every minute

Exactly.

> in my case i am on windows have Task scheduler App not cron ?

Yes.

`TestTasks.php` file should be in `tasks` directory and calling `vendor\bin\crunz schedule:list` should show this file.

**Comment by PabloKowalczyk** [comment]
Anyway, this issue is not related to Crunz code itself so i will close this issue, but you can write in this thread if you need help.
